// SPDX-License-Identifier: Apache-2.0
pragma solidity 0.8.28;

import {Test, Vm} from "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";
import {IssuerRegistry} from "../src/IssuerRegistry.sol";
import {DogTagIssuer} from "../src/DogTagIssuer.sol";
import {DogTagIssuerFactory} from "../src/DogTagIssuerFactory.sol";
import {DogTagSBT} from "../src/DogTagSBT.sol";
import {VerificationRegistryConsent} from "../src/VerificationRegistryConsent.sol";
import {Groth16VerifierConsent} from "../src/Groth16VerifierConsent.sol";

/// @notice M4 acceptance: a REAL Groth16 proof from circuits/consent.circom (proved against the
/// PRODUCTION M3 ceremony key) verifies on-chain through VerificationRegistryConsent and emits an
/// OWNER-BLIND `Verified`, with the registry binding `R == profileRoot(dogTagId)`, consuming the
/// nullifier, and consulting NO owner IDENTITY - no `ownerOf == subject` comparison, no `keyOf`
/// (`ownerOf` is called only as an existence gate, value discarded).
/// Fixture (a,b,c,pub) generated by `node circuits/scripts/gen-consent-fixture.mjs`.
contract ConsentRegistryTest is Test {
    using stdJson for string;

    IssuerRegistry registry;
    DogTagIssuerFactory factory;
    DogTagSBT sbt;
    VerificationRegistryConsent vr;
    Groth16VerifierConsent verifier;

    address admin = address(0xA11CE);
    address vetSigner = address(0xBEEF);
    /// @dev D1: the Level-B tag is minted to a NEUTRAL CUSTODIAN, never the owner. Every test here
    /// runs against a tag whose `ownerOf` is this address — so if the registry ever reintroduced an
    /// `ownerOf == subject` check, the whole suite would fail rather than silently pass.
    address custodian = address(0xC0FFEE);

    uint256 constant SNARK_SCALAR_FIELD =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;
    bytes32 constant VACCINATION = keccak256("VACCINATION");

    uint256[2] a;
    uint256[2][2] b;
    uint256[2] c;
    uint256[7] pub;

    // art9 = the same witness with recordType = keccak256("SERVICE_ATTESTATION") % r.
    uint256[2] a9;
    uint256[2][2] b9;
    uint256[2] c9;
    uint256[7] pub9;

    uint256 dogTagId;
    bytes32 purpose;
    address relayer;
    bytes32 nullifier;
    bytes32 root;
    uint256 deadline;
    address ownerAddress; // the hidden owner — must NEVER appear on-chain

    function setUp() public {
        string memory j = vm.readFile("test/consent-fixture.json");
        (a, b, c, pub) = _readProof(j, "");
        (a9, b9, c9, pub9) = _readProof(j, ".art9");

        dogTagId = pub[0];
        purpose = bytes32(pub[1]);
        relayer = address(uint160(pub[2]));
        nullifier = bytes32(pub[3]);
        root = bytes32(pub[4]);
        deadline = pub[6];
        ownerAddress = j.readAddress("._ownerAddress");

        vm.startPrank(admin);
        registry = new IssuerRegistry(admin);
        DogTagIssuer impl = new DogTagIssuer();
        factory = new DogTagIssuerFactory(address(impl), address(registry), admin);
        sbt = new DogTagSBT(admin);
        verifier = new Groth16VerifierConsent();
        vr = new VerificationRegistryConsent(
            address(registry), address(sbt), address(verifier), address(factory), admin
        );
        vm.stopPrank();

        // Issue the per-tag root R on a VACCINATION clone (populates the write-once rootIssuer[R]).
        vm.prank(admin);
        DogTagIssuer vacc = DogTagIssuer(factory.createIssuer("Vacc", VACCINATION, vetSigner));
        vm.prank(admin);
        registry.whitelistFor(VACCINATION, vetSigner);
        vm.prank(vetSigner);
        vacc.issue(root);

        // Mint the tag to the CUSTODIAN with profileRoot = R (the Level-B anchor).
        // Read the role BEFORE pranking: vm.prank only survives to the next CALL, and
        // `sbt.ISSUER_ROLE()` would otherwise consume it.
        bytes32 issuerRole = sbt.ISSUER_ROLE();
        vm.prank(admin);
        sbt.grantRole(issuerRole, address(this));
        sbt.mint(custodian, dogTagId, root);

        vm.prank(admin);
        registry.whitelistFor(keccak256(abi.encode("VERIFY:", purpose)), relayer);
    }

    function _readProof(string memory j, string memory p)
        internal
        pure
        returns (uint256[2] memory a_, uint256[2][2] memory b_, uint256[2] memory c_, uint256[7] memory pub_)
    {
        uint256[] memory av = j.readUintArray(string.concat(p, ".a"));
        uint256[] memory b0 = j.readUintArray(string.concat(p, ".b[0]"));
        uint256[] memory b1 = j.readUintArray(string.concat(p, ".b[1]"));
        uint256[] memory cv = j.readUintArray(string.concat(p, ".c"));
        uint256[] memory pv = j.readUintArray(string.concat(p, ".pub"));
        a_ = [av[0], av[1]];
        b_ = [[b0[0], b0[1]], [b1[0], b1[1]]];
        c_ = [cv[0], cv[1]];
        for (uint256 i; i < 7; i++) {
            pub_[i] = pv[i];
        }
    }

    // ---- the happy path ----

    function test_real_proof_records_owner_blind_verified() public {
        assertTrue(verifier.verifyProof(a, b, c, pub), "real proof must verify");

        vm.expectEmit(true, true, true, true);
        emit VerificationRegistryConsent.Verified(
            dogTagId, relayer, purpose, nullifier, deadline, block.timestamp
        );
        vm.prank(relayer);
        vr.recordVerificationZK(a, b, c, pub);
        assertTrue(vr.consumed(nullifier), "nullifier must be consumed");
    }

    /// @notice D1: `ownerOf(dogTagId)` is the custodian, NOT the owner — and verification passes anyway.
    /// This is the property the whole Level-B redesign exists for. The registry DOES call `ownerOf` (an
    /// existence gate, value discarded - see `test_burned_tag_cannot_verify`), but never COMPARES it: a
    /// reintroduced `ownerOf == subject` check would fail this test rather than silently pass.
    function test_owner_identity_is_never_read_from_chain() public {
        assertEq(sbt.ownerOf(dogTagId), custodian, "Level-B tags are custodial");
        assertTrue(sbt.ownerOf(dogTagId) != ownerAddress, "custodian must not be the owner");
        vm.prank(relayer);
        vr.recordVerificationZK(a, b, c, pub); // would revert if any ownerOf==subject/keyOf check survived
    }

    /// @notice GDPR-erasure must stop verification. `DogTagSBT.burn` clears the ownerOf<->wallet link but
    /// NOT `profileRoot[id]`, so the `R == profileRoot` binding still passes for an erased tag - the
    /// registry's `ownerOf` existence gate is the only thing that fails it closed. Without that gate an
    /// erased tag keeps emitting `Verified` until someone separately calls `revoke(R)`.
    function test_burned_tag_cannot_verify() public {
        vm.prank(admin);
        sbt.burn(dogTagId);

        // Exactly why the existence gate is load-bearing rather than redundant: the binding SURVIVES.
        assertEq(sbt.profileRoot(dogTagId), root, "burn does not clear profileRoot");

        vm.prank(relayer);
        vm.expectRevert(); // ERC721NonexistentToken - the erased token has no owner
        vr.recordVerificationZK(a, b, c, pub);
    }

    /// @notice The owner's address must not be recoverable from the transaction: not in the public
    /// signals, not in the emitted event. `subject` used to be pub[3] and an indexed event arg.
    function test_owner_address_absent_from_calldata_and_logs() public {
        for (uint256 i; i < 7; i++) {
            assertTrue(pub[i] != uint256(uint160(ownerAddress)), "owner leaked into a public signal");
        }

        vm.recordLogs();
        vm.prank(relayer);
        vr.recordVerificationZK(a, b, c, pub);
        Vm.Log[] memory logs = vm.getRecordedLogs();
        assertEq(logs.length, 1, "exactly one Verified event");

        bytes32 ownerWord = bytes32(uint256(uint160(ownerAddress)));
        for (uint256 t; t < logs[0].topics.length; t++) {
            assertTrue(logs[0].topics[t] != ownerWord, "owner leaked into an event topic");
        }
        // The event carries 3 non-indexed words (purpose, nullifier, deadline, ts -> 4). None is the owner.
        bytes memory d = logs[0].data;
        for (uint256 o; o + 32 <= d.length; o += 32) {
            bytes32 w;
            assembly {
                w := mload(add(add(d, 0x20), o))
            }
            assertTrue(w != ownerWord, "owner leaked into event data");
        }
    }

    // ---- the Level-B binding: R == profileRoot(dogTagId) ----

    /// @notice The circuit does NOT bind dogTagId <-> R, so this on-chain check is the ONLY thing
    /// stopping a prover from folding a tree they fully control and consenting as someone else's tag.
    function test_R_must_equal_profileRoot() public {
        bytes32 authorityRole = sbt.AUTHORITY_ROLE();
        vm.prank(admin);
        sbt.grantRole(authorityRole, admin);
        vm.prank(admin);
        sbt.setProfileRoot(dogTagId, keccak256("some other root"));

        vm.prank(relayer);
        vm.expectRevert("R !profileRoot");
        vr.recordVerificationZK(a, b, c, pub);
    }

    /// @notice An unminted tag has profileRoot == 0, which must not be satisfiable by any proof.
    function test_unminted_tag_cannot_verify() public {
        uint256 other = dogTagId + 1;
        assertEq(sbt.profileRoot(other), bytes32(0));
        uint256[7] memory p = pub;
        p[0] = other;
        vm.prank(relayer);
        vm.expectRevert("R !profileRoot");
        vr.recordVerificationZK(a, b, c, p);
    }

    // ---- D5 nullifier ----

    function test_replay_of_same_consent_reverts() public {
        vm.prank(relayer);
        vr.recordVerificationZK(a, b, c, pub);
        vm.prank(relayer);
        vm.expectRevert("replayed");
        vr.recordVerificationZK(a, b, c, pub);
    }

    // ---- guards ----

    function test_only_the_bound_relayer_may_submit() public {
        vm.prank(address(0xDEAD));
        vm.expectRevert("not relayer");
        vr.recordVerificationZK(a, b, c, pub);
    }

    function test_expired_consent_reverts() public {
        vm.warp(deadline + 1);
        vm.prank(relayer);
        vm.expectRevert("expired");
        vr.recordVerificationZK(a, b, c, pub);
    }

    function test_unwhitelisted_relayer_reverts() public {
        vm.prank(admin);
        registry.delistFor(keccak256(abi.encode("VERIFY:", purpose)), relayer);
        vm.prank(relayer);
        vm.expectRevert("!verify-wl");
        vr.recordVerificationZK(a, b, c, pub);
    }

    function test_revoked_root_reverts() public {
        DogTagIssuer vacc = DogTagIssuer(factory.rootIssuer(root));
        vm.prank(vetSigner);
        vacc.revoke(root);
        vm.prank(relayer);
        vm.expectRevert("cred !valid");
        vr.recordVerificationZK(a, b, c, pub);
    }

    function test_tampered_proof_rejected() public {
        uint256[2] memory aBad = [a[0] ^ 1, a[1]];
        vm.prank(relayer);
        vm.expectRevert();
        vr.recordVerificationZK(aBad, b, c, pub);
    }

    /// @notice A tampered public signal must not verify. `R` is checked against profileRoot BEFORE the
    /// proof, so tamper `deadline` (unconstrained on-chain beyond expiry) to reach `verifyProof`.
    function test_tampered_public_signal_rejected() public {
        uint256[7] memory p = pub;
        p[6] = deadline + 1;
        vm.prank(relayer);
        vm.expectRevert("bad proof");
        vr.recordVerificationZK(a, b, c, p);
    }

    // ---- Art. 9 ----

    /// @notice The Art.9 guard must fire on a REAL proof whose recordType is SERVICE_ATTESTATION.
    /// Level-A compared the RAW `keccak256("SERVICE_ATTESTATION")`; as a public SIGNAL the value is
    /// reduced mod r, and the raw keccak EXCEEDS r — so the raw constant could never match and the
    /// guard would be dead code. This test fails if that regression is reintroduced.
    function test_art9_service_attestation_rejected_on_real_proof() public {
        assertTrue(verifier.verifyProof(a9, b9, c9, pub9), "art9 fixture must be a valid proof");
        vm.prank(admin);
        registry.whitelistFor(keccak256(abi.encode("VERIFY:", bytes32(pub9[1]))), relayer);
        vm.prank(relayer);
        vm.expectRevert(bytes("art9")); // 4-byte literal: disambiguate from the bytes4 overload
        vr.recordVerificationZK(a9, b9, c9, pub9);
    }

    /// @dev Pins the reduced constant against Solidity's own keccak — the drift guard for the value
    /// hardcoded in the contract AND in gen-consent-fixture.mjs.
    function test_service_attestation_field_constant_is_the_reduction() public pure {
        uint256 reduced = uint256(keccak256("SERVICE_ATTESTATION")) % SNARK_SCALAR_FIELD;
        assertEq(
            reduced,
            10025591956217394737855806998434905929145386518960477508456501950324730293568,
            "SERVICE_ATTESTATION_FIELD drifted"
        );
        assertTrue(uint256(keccak256("SERVICE_ATTESTATION")) > SNARK_SCALAR_FIELD, "raw keccak > r");
    }

    /// @dev The fixture's labels really are `keccak256(label) % r`, so the vector the registry indexes
    /// matches what the apps will send.
    function test_fixture_labels_are_reduced_keccak() public view {
        assertEq(pub[1], uint256(keccak256("GROOMING_INTAKE")) % SNARK_SCALAR_FIELD, "purpose");
        assertEq(pub[5], uint256(keccak256("VACCINATION")) % SNARK_SCALAR_FIELD, "recordType");
        assertEq(pub9[5], uint256(keccak256("SERVICE_ATTESTATION")) % SNARK_SCALAR_FIELD, "art9");
    }
}
