// SPDX-License-Identifier: Apache-2.0
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";
import {IssuerRegistry} from "../src/IssuerRegistry.sol";
import {DogTagIssuer} from "../src/DogTagIssuer.sol";
import {DogTagIssuerFactory} from "../src/DogTagIssuerFactory.sol";
import {DogTagSBT} from "../src/DogTagSBT.sol";
import {ConsentKeyRegistry} from "../src/ConsentKeyRegistry.sol";
import {VerificationRegistry, IPoseidon6} from "../src/VerificationRegistry.sol";
import {Groth16Verifier} from "../src/Groth16Verifier.sol";

/// @notice Phase 2.5 acceptance: a REAL Groth16 proof from circuits/verification.circom verifies
/// on-chain through VerificationRegistry.recordVerificationZK and emits Verified, with the registry
/// checking subject<->key, ownerOf==subject, the write-once rootIssuer[R] resolution, and isValid(R)
/// directly. Fixture (a,b,c,pub) generated by `circuits/scripts/gen-zk-fixture.mjs`.
contract ZkIntegrationTest is Test {
    using stdJson for string;

    IssuerRegistry registry;
    DogTagIssuerFactory factory;
    DogTagSBT sbt;
    ConsentKeyRegistry consentKeys;
    VerificationRegistry vr;
    Groth16Verifier verifier;
    IPoseidon6 poseidon6;

    address admin = address(0xA11CE);
    address vetSigner = address(0xBEEF);
    bytes32 constant VACCINATION = keccak256("VACCINATION");
    bytes32 constant SERVICE_ATTESTATION = keccak256("SERVICE_ATTESTATION");
    uint256 constant TWO_POW_160 = 1 << 160;

    uint256[2] a;
    uint256[2][2] b;
    uint256[2] c;
    uint256[7] pub;

    address relayer;
    address subject;
    uint256 subjectPk = 1; // subject == vm.addr(1) by construction of the fixture
    uint256 dogTagId;
    bytes32 purpose;
    bytes32 keyHash;
    bytes32 root;

    function setUp() public {
        string memory j = vm.readFile("test/zk-fixture.json");
        uint256[] memory av = j.readUintArray(".a");
        uint256[] memory b0 = j.readUintArray(".b[0]");
        uint256[] memory b1 = j.readUintArray(".b[1]");
        uint256[] memory cv = j.readUintArray(".c");
        uint256[] memory pv = j.readUintArray(".pub");
        a = [av[0], av[1]];
        b = [[b0[0], b0[1]], [b1[0], b1[1]]];
        c = [cv[0], cv[1]];
        for (uint256 i; i < 7; i++) {
            pub[i] = pv[i];
        }
        dogTagId = pub[0];
        purpose = bytes32(pub[1]);
        relayer = address(uint160(pub[2]));
        subject = address(uint160(pub[3]));
        keyHash = bytes32(pub[5]);
        root = bytes32(pub[6]);
        require(subject == vm.addr(subjectPk), "fixture subject != vm.addr(1)");

        vm.startPrank(admin);
        registry = new IssuerRegistry(admin);
        DogTagIssuer impl = new DogTagIssuer();
        factory = new DogTagIssuerFactory(address(impl), address(registry), admin);
        sbt = new DogTagSBT(admin);
        consentKeys = new ConsentKeyRegistry();
        verifier = new Groth16Verifier();
        vm.stopPrank();

        bytes memory initcode = vm.parseBytes(vm.readFile("test/poseidon6.initcode"));
        address p6;
        assembly {
            p6 := create(0, add(initcode, 0x20), mload(initcode))
        }
        poseidon6 = IPoseidon6(p6);

        vm.prank(admin);
        vr = new VerificationRegistry(
            address(registry),
            address(sbt),
            address(verifier),
            address(consentKeys),
            address(factory),
            p6,
            admin
        );

        // issue the credential root R on a VACCINATION clone
        vm.prank(admin);
        DogTagIssuer vacc = DogTagIssuer(factory.createIssuer("Vacc", VACCINATION, vetSigner));
        vm.prank(admin);
        registry.whitelistFor(VACCINATION, vetSigner);
        vm.prank(vetSigner);
        vacc.issue(root);

        // mint the pet SBT to subject
        bytes32 issuerRole = sbt.ISSUER_ROLE();
        vm.prank(admin);
        sbt.grantRole(issuerRole, address(this));
        sbt.mint(subject, dogTagId, keccak256("profile"));

        // bind the consent key for subject via the REAL ECDSA path
        _bindKey();

        // authorize the relayer for this purpose
        vm.prank(admin);
        registry.whitelistFor(keccak256(abi.encode("VERIFY:", purpose)), relayer);
    }

    function _bindKey() internal {
        uint256 nonce = consentKeys.bindNonce(subject);
        bytes32 domainSep = keccak256(
            abi.encode(
                keccak256(
                    "EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"
                ),
                keccak256(bytes("DogTag")),
                keccak256(bytes("1")),
                block.chainid,
                address(consentKeys)
            )
        );
        bytes32 structHash = keccak256(
            abi.encode(
                keccak256("BindConsentKey(bytes32 babyJubPubKeyHash,address wallet,uint256 nonce)"),
                keyHash,
                subject,
                nonce
            )
        );
        bytes32 digest = keccak256(abi.encodePacked("\x19\x01", domainSep, structHash));
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(subjectPk, digest);
        vm.prank(subject);
        consentKeys.bindConsentKey(keyHash, abi.encodePacked(r, s, v));
    }

    function test_real_proof_records_verified() public {
        assertTrue(verifier.verifyProof(a, b, c, pub), "real proof must verify");

        vm.expectEmit(true, true, true, true);
        emit VerificationRegistry.Verified(
            dogTagId, relayer, subject, purpose, bytes32(pub[4]), block.timestamp
        );
        vm.prank(relayer);
        vr.recordVerificationZK(a, b, c, pub, VACCINATION, block.timestamp + 1 hours);
        assertTrue(vr.consumed(bytes32(pub[4])));
    }

    function test_real_proof_replay_reverts() public {
        vm.prank(relayer);
        vr.recordVerificationZK(a, b, c, pub, VACCINATION, block.timestamp + 1 hours);
        vm.prank(relayer);
        vm.expectRevert("replayed");
        vr.recordVerificationZK(a, b, c, pub, VACCINATION, block.timestamp + 1 hours);
    }

    function test_malleated_proof_rejected_by_verifier() public {
        uint256[2] memory aBad = [a[0] ^ 1, a[1]]; // flip a bit -> not a valid proof point
        vm.prank(relayer);
        vm.expectRevert(); // Groth16Verifier reverts on a malformed point, or verifyProof returns false -> "bad proof"
        vr.recordVerificationZK(aBad, b, c, pub, VACCINATION, block.timestamp + 1 hours);
    }

    // ---- audit L1: address-typed signals must fit in 160 bits ----
    // A prover can pick `pub[i] = victim + k·2^160 < r`: the on-chain `uint160(pub[i])` truncation
    // aliases `victim` (so the relayer/owner checks pass) while the proof witnesses the FULL field
    // element. The `pub[2/3] < TWO_POW_160` guard rejects this before any address cast is trusted.
    function test_aliased_relayer_pub_reverts() public {
        uint256[7] memory p = _pubCopy();
        p[2] = pub[2] + TWO_POW_160; // truncates back to `relayer`, but is now >= 2^160
        require(address(uint160(p[2])) == relayer, "alias precondition: truncates to relayer");
        require(p[2] < vrField(), "alias precondition: still < r");
        vm.prank(relayer);
        vm.expectRevert("addr range");
        vr.recordVerificationZK(a, b, c, p, VACCINATION, block.timestamp + 1 hours);
    }

    function test_aliased_subject_pub_reverts() public {
        uint256[7] memory p = _pubCopy();
        p[3] = pub[3] + TWO_POW_160; // truncates back to `subject`, but is now >= 2^160
        require(address(uint160(p[3])) == subject, "alias precondition: truncates to subject");
        vm.prank(relayer);
        vm.expectRevert("addr range");
        vr.recordVerificationZK(a, b, c, p, VACCINATION, block.timestamp + 1 hours);
    }

    // ---- audit L2: explicit deadline + Art. 9 exclusion mirroring the normal path ----
    function test_expired_deadline_reverts() public {
        vm.warp(1000);
        vm.prank(relayer);
        vm.expectRevert("expired");
        vr.recordVerificationZK(a, b, c, pub, VACCINATION, 999);
    }

    function test_service_attestation_record_type_reverts() public {
        vm.prank(relayer);
        vm.expectRevert(bytes("art9"));
        vr.recordVerificationZK(a, b, c, pub, SERVICE_ATTESTATION, block.timestamp + 1 hours);
    }

    function _pubCopy() internal view returns (uint256[7] memory p) {
        for (uint256 i; i < 7; i++) {
            p[i] = pub[i];
        }
    }

    function vrField() internal pure returns (uint256) {
        return 21888242871839275222246405745257275088548364400416034343698204186575808495617; // BN254 r
    }
}
