// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(dogtag_standardFFI)
import dogtag_standardFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_dogtag_standard_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_dogtag_standard_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


/**
 * A disclosable attribute leaf crossing the FFI boundary. `tag`+`value` are reconstructed into a
 * `TypedScalar` exactly like `hash_leaf_hex` does. `salt_hex` is 16 bytes.
 */
public struct AttributeLeafFfi {
    public var keyPath: String
    public var saltHex: String
    public var tag: UInt8
    public var value: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(keyPath: String, saltHex: String, tag: UInt8, value: String) {
        self.keyPath = keyPath
        self.saltHex = saltHex
        self.tag = tag
        self.value = value
    }
}



extension AttributeLeafFfi: Equatable, Hashable {
    public static func ==(lhs: AttributeLeafFfi, rhs: AttributeLeafFfi) -> Bool {
        if lhs.keyPath != rhs.keyPath {
            return false
        }
        if lhs.saltHex != rhs.saltHex {
            return false
        }
        if lhs.tag != rhs.tag {
            return false
        }
        if lhs.value != rhs.value {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(keyPath)
        hasher.combine(saltHex)
        hasher.combine(tag)
        hasher.combine(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAttributeLeafFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AttributeLeafFfi {
        return
            try AttributeLeafFfi(
                keyPath: FfiConverterString.read(from: &buf), 
                saltHex: FfiConverterString.read(from: &buf), 
                tag: FfiConverterUInt8.read(from: &buf), 
                value: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: AttributeLeafFfi, into buf: inout [UInt8]) {
        FfiConverterString.write(value.keyPath, into: &buf)
        FfiConverterString.write(value.saltHex, into: &buf)
        FfiConverterUInt8.write(value.tag, into: &buf)
        FfiConverterString.write(value.value, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAttributeLeafFfi_lift(_ buf: RustBuffer) throws -> AttributeLeafFfi {
    return try FfiConverterTypeAttributeLeafFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAttributeLeafFfi_lower(_ value: AttributeLeafFfi) -> RustBuffer {
    return FfiConverterTypeAttributeLeafFfi.lower(value)
}


/**
 * The CONVENIENCE tier (§5.2): the platform-OWNED claims a resolve GET returns. NONE of these is
 * authority — every trust-critical field is validated against the [`TrustedAnchor`] before use
 * ([`validate`]). Serialized camelCase so it is the exact nested `unverifiedClaims` block the resolve GET emits
 * and the app deserializes.
 */
public struct ConvenienceClaims {
    /**
     * CLAIMED protocol version, e.g. `dogtag-levelb/1`. The app resolves the anchor BY this string.
     */
    public var protocolVersion: String
    /**
     * CLAIMED chain id. A lying platform would forge this to point at a fork/testnet.
     */
    public var chainId: UInt64
    /**
     * CLAIMED verification registry address — THE redirect target a lying platform would forge.
     */
    public var verificationRegistry: String
    /**
     * CLAIMED issuer clone (documentStore) the platform will issue/verify against. Carried for the app;
     * it is NOT a trust-tier axis — the on-chain re-derivation binds the clone from `rootIssuer[R]`
     * (§4.3), so a forged `issuerClone` cannot make an invalid record verify.
     */
    public var issuerClone: String
    /**
     * CLAIMED purpose (the verify-gate namespace / consent purpose). Checked against the app's
     * out-of-band expected purpose ([`ClientContext::expected_purpose`]), never the platform's session.
     */
    public var purpose: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * CLAIMED protocol version, e.g. `dogtag-levelb/1`. The app resolves the anchor BY this string.
         */protocolVersion: String, 
        /**
         * CLAIMED chain id. A lying platform would forge this to point at a fork/testnet.
         */chainId: UInt64, 
        /**
         * CLAIMED verification registry address — THE redirect target a lying platform would forge.
         */verificationRegistry: String, 
        /**
         * CLAIMED issuer clone (documentStore) the platform will issue/verify against. Carried for the app;
         * it is NOT a trust-tier axis — the on-chain re-derivation binds the clone from `rootIssuer[R]`
         * (§4.3), so a forged `issuerClone` cannot make an invalid record verify.
         */issuerClone: String, 
        /**
         * CLAIMED purpose (the verify-gate namespace / consent purpose). Checked against the app's
         * out-of-band expected purpose ([`ClientContext::expected_purpose`]), never the platform's session.
         */purpose: String) {
        self.protocolVersion = protocolVersion
        self.chainId = chainId
        self.verificationRegistry = verificationRegistry
        self.issuerClone = issuerClone
        self.purpose = purpose
    }
}



extension ConvenienceClaims: Equatable, Hashable {
    public static func ==(lhs: ConvenienceClaims, rhs: ConvenienceClaims) -> Bool {
        if lhs.protocolVersion != rhs.protocolVersion {
            return false
        }
        if lhs.chainId != rhs.chainId {
            return false
        }
        if lhs.verificationRegistry != rhs.verificationRegistry {
            return false
        }
        if lhs.issuerClone != rhs.issuerClone {
            return false
        }
        if lhs.purpose != rhs.purpose {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(protocolVersion)
        hasher.combine(chainId)
        hasher.combine(verificationRegistry)
        hasher.combine(issuerClone)
        hasher.combine(purpose)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConvenienceClaims: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConvenienceClaims {
        return
            try ConvenienceClaims(
                protocolVersion: FfiConverterString.read(from: &buf), 
                chainId: FfiConverterUInt64.read(from: &buf), 
                verificationRegistry: FfiConverterString.read(from: &buf), 
                issuerClone: FfiConverterString.read(from: &buf), 
                purpose: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ConvenienceClaims, into buf: inout [UInt8]) {
        FfiConverterString.write(value.protocolVersion, into: &buf)
        FfiConverterUInt64.write(value.chainId, into: &buf)
        FfiConverterString.write(value.verificationRegistry, into: &buf)
        FfiConverterString.write(value.issuerClone, into: &buf)
        FfiConverterString.write(value.purpose, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConvenienceClaims_lift(_ buf: RustBuffer) throws -> ConvenienceClaims {
    return try FfiConverterTypeConvenienceClaims.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConvenienceClaims_lower(_ value: ConvenienceClaims) -> RustBuffer {
    return FfiConverterTypeConvenienceClaims.lower(value)
}


/**
 * A device-built per-tag profile tree.
 *
 * Everything here except `root_hex` is OWNER-PRIVATE and must never be transmitted: only
 * `root_hex` (`R`) is handed to the issuer, which seals it as `profileRoot(dogTagId)`.
 */
public struct ProfileTreeFfi {
    /**
     * `R` - the value the issuer seals as `profileRoot(dogTagId)`.
     */
    public var rootHex: String
    /**
     * The nullifier secret. Regenerable from the wallet seed; keep it device-local and never send
     * or back it up separately.
     */
    public var ownerSecretHex: String
    public var axHex: String
    public var ayHex: String
    public var consentPrvHex: String
    public var keyHashHex: String
    public var ownerSaltHex: String
    public var keySaltHex: String
    public var secretSaltHex: String
    public var ownerAddressLeafHex: String
    public var consentKeyLeafHex: String
    public var ownerSecretLeafHex: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * `R` - the value the issuer seals as `profileRoot(dogTagId)`.
         */rootHex: String, 
        /**
         * The nullifier secret. Regenerable from the wallet seed; keep it device-local and never send
         * or back it up separately.
         */ownerSecretHex: String, axHex: String, ayHex: String, consentPrvHex: String, keyHashHex: String, ownerSaltHex: String, keySaltHex: String, secretSaltHex: String, ownerAddressLeafHex: String, consentKeyLeafHex: String, ownerSecretLeafHex: String) {
        self.rootHex = rootHex
        self.ownerSecretHex = ownerSecretHex
        self.axHex = axHex
        self.ayHex = ayHex
        self.consentPrvHex = consentPrvHex
        self.keyHashHex = keyHashHex
        self.ownerSaltHex = ownerSaltHex
        self.keySaltHex = keySaltHex
        self.secretSaltHex = secretSaltHex
        self.ownerAddressLeafHex = ownerAddressLeafHex
        self.consentKeyLeafHex = consentKeyLeafHex
        self.ownerSecretLeafHex = ownerSecretLeafHex
    }
}



extension ProfileTreeFfi: Equatable, Hashable {
    public static func ==(lhs: ProfileTreeFfi, rhs: ProfileTreeFfi) -> Bool {
        if lhs.rootHex != rhs.rootHex {
            return false
        }
        if lhs.ownerSecretHex != rhs.ownerSecretHex {
            return false
        }
        if lhs.axHex != rhs.axHex {
            return false
        }
        if lhs.ayHex != rhs.ayHex {
            return false
        }
        if lhs.consentPrvHex != rhs.consentPrvHex {
            return false
        }
        if lhs.keyHashHex != rhs.keyHashHex {
            return false
        }
        if lhs.ownerSaltHex != rhs.ownerSaltHex {
            return false
        }
        if lhs.keySaltHex != rhs.keySaltHex {
            return false
        }
        if lhs.secretSaltHex != rhs.secretSaltHex {
            return false
        }
        if lhs.ownerAddressLeafHex != rhs.ownerAddressLeafHex {
            return false
        }
        if lhs.consentKeyLeafHex != rhs.consentKeyLeafHex {
            return false
        }
        if lhs.ownerSecretLeafHex != rhs.ownerSecretLeafHex {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(rootHex)
        hasher.combine(ownerSecretHex)
        hasher.combine(axHex)
        hasher.combine(ayHex)
        hasher.combine(consentPrvHex)
        hasher.combine(keyHashHex)
        hasher.combine(ownerSaltHex)
        hasher.combine(keySaltHex)
        hasher.combine(secretSaltHex)
        hasher.combine(ownerAddressLeafHex)
        hasher.combine(consentKeyLeafHex)
        hasher.combine(ownerSecretLeafHex)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProfileTreeFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProfileTreeFfi {
        return
            try ProfileTreeFfi(
                rootHex: FfiConverterString.read(from: &buf), 
                ownerSecretHex: FfiConverterString.read(from: &buf), 
                axHex: FfiConverterString.read(from: &buf), 
                ayHex: FfiConverterString.read(from: &buf), 
                consentPrvHex: FfiConverterString.read(from: &buf), 
                keyHashHex: FfiConverterString.read(from: &buf), 
                ownerSaltHex: FfiConverterString.read(from: &buf), 
                keySaltHex: FfiConverterString.read(from: &buf), 
                secretSaltHex: FfiConverterString.read(from: &buf), 
                ownerAddressLeafHex: FfiConverterString.read(from: &buf), 
                consentKeyLeafHex: FfiConverterString.read(from: &buf), 
                ownerSecretLeafHex: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ProfileTreeFfi, into buf: inout [UInt8]) {
        FfiConverterString.write(value.rootHex, into: &buf)
        FfiConverterString.write(value.ownerSecretHex, into: &buf)
        FfiConverterString.write(value.axHex, into: &buf)
        FfiConverterString.write(value.ayHex, into: &buf)
        FfiConverterString.write(value.consentPrvHex, into: &buf)
        FfiConverterString.write(value.keyHashHex, into: &buf)
        FfiConverterString.write(value.ownerSaltHex, into: &buf)
        FfiConverterString.write(value.keySaltHex, into: &buf)
        FfiConverterString.write(value.secretSaltHex, into: &buf)
        FfiConverterString.write(value.ownerAddressLeafHex, into: &buf)
        FfiConverterString.write(value.consentKeyLeafHex, into: &buf)
        FfiConverterString.write(value.ownerSecretLeafHex, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProfileTreeFfi_lift(_ buf: RustBuffer) throws -> ProfileTreeFfi {
    return try FfiConverterTypeProfileTreeFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProfileTreeFfi_lower(_ value: ProfileTreeFfi) -> RustBuffer {
    return FfiConverterTypeProfileTreeFfi.lower(value)
}


/**
 * A Groth16 proof formatted exactly as the on-chain Solidity calldata expects (mirrors
 * `dogtag-prover-rs::Groth16Output`): `a`/`c` are G1 `[x,y]`; `b` is G2 with the snarkjs->Solidity
 * coordinate swap applied (`b[0]=[bx_c1,bx_c0]`, `b[1]=[by_c1,by_c0]`); `pub_signals` is the
 * 7-element output vector. All values are base-10 decimal strings.
 */
public struct ProofFfi {
    public var a: [String]
    public var b: [[String]]
    public var c: [String]
    public var pubSignals: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(a: [String], b: [[String]], c: [String], pubSignals: [String]) {
        self.a = a
        self.b = b
        self.c = c
        self.pubSignals = pubSignals
    }
}



extension ProofFfi: Equatable, Hashable {
    public static func ==(lhs: ProofFfi, rhs: ProofFfi) -> Bool {
        if lhs.a != rhs.a {
            return false
        }
        if lhs.b != rhs.b {
            return false
        }
        if lhs.c != rhs.c {
            return false
        }
        if lhs.pubSignals != rhs.pubSignals {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(a)
        hasher.combine(b)
        hasher.combine(c)
        hasher.combine(pubSignals)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProofFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProofFfi {
        return
            try ProofFfi(
                a: FfiConverterSequenceString.read(from: &buf), 
                b: FfiConverterSequenceSequenceString.read(from: &buf), 
                c: FfiConverterSequenceString.read(from: &buf), 
                pubSignals: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: ProofFfi, into buf: inout [UInt8]) {
        FfiConverterSequenceString.write(value.a, into: &buf)
        FfiConverterSequenceSequenceString.write(value.b, into: &buf)
        FfiConverterSequenceString.write(value.c, into: &buf)
        FfiConverterSequenceString.write(value.pubSignals, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProofFfi_lift(_ buf: RustBuffer) throws -> ProofFfi {
    return try FfiConverterTypeProofFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProofFfi_lower(_ value: ProofFfi) -> RustBuffer {
    return FfiConverterTypeProofFfi.lower(value)
}


/**
 * The dogtag-owned TRUST tier (§5.2) for one version, RESOLVED by the caller from
 * `ProtocolRegistry.getContractSet` + `getActiveArtifactSet` (root of truth) or the P3 signed-manifest
 * fallback (both mirror the same two on-chain axes). These are the AUTHORITATIVE values a platform's
 * [`ConvenienceClaims`] are
 * checked against. Constructed from plain fields so the app can build it from an `eth_call` result or a
 * parsed/reconciled manifest, and the server can map it from `dogtag_prover::manifest` types — keeping
 * this crate free of any prover/manifest dependency.
 */
public struct TrustedAnchor {
    /**
     * The version string this record certifies (e.g. `dogtag-levelb/1`).
     */
    public var version: String
    /**
     * keccak256(version) `0x`-hex — the on-chain `contractSetId`; ties the claimed version STRING to
     * the on-chain key so a caller cannot silently validate against the wrong record.
     */
    public var versionId: String
    /**
     * The ARTIFACT-AXIS identity the caller resolved for this version (e.g.
     * `dogtag-levelb-artifacts/1`) — the artifact set `activeArtifactSetOf[versionId]` points at.
     *
     * It is a SECOND, independent axis (R-5): rotating the proving artifacts changes this and
     * `min_app_version` while `version`/`version_id` and `verification_registry` stay put. Carrying it
     * on the anchor is what lets a caller say WHICH artifact set it is about to fetch, rather than
     * inferring it from the version.
     */
    public var artifactSet: String
    /**
     * keccak256(artifact_set) `0x`-hex — the on-chain `artifactSetId`. A DIFFERENT keyspace from
     * `version_id`; [`validate`] checks their coherence independently.
     */
    public var artifactSetId: String
    /**
     * The chain the trio lives on. (Carried by the manifest / known by the app from its RPC endpoint;
     * the on-chain `ContractSet` struct itself has no chain-id member — the registry IS on a chain.)
     */
    public var chainId: UInt64
    /**
     * The registry a proof is submitted to (trio leg). The anti-redirect anchor.
     */
    public var verificationRegistry: String
    /**
     * The circuit this version proves (`<source>/<template>(<params>)`) — the artifact-selection key
     * (§5.3 step 6; version↔circuit_id is 1:1 in `dogtag_prover::artifact`).
     */
    public var circuitId: String
    /**
     * Minimum app build (semver) allowed to use this version — the deprecation lever (§5.3 step 5).
     */
    public var minAppVersion: String
    /**
     * The ON-CHAIN axis's lifecycle bit — `ContractSet.active`, as read from
     * `ProtocolRegistry.getContractSet`. `deprecateContractSet` flips it false.
     *
     * It is an INDEPENDENT kill switch, and [`validate`] requires BOTH it and
     * [`Self::artifact_set_active`] to be true. Populate the two SEPARATELY from the two on-chain
     * records — never AND them into one field and never wire only one: R-5 splits the axes precisely so
     * each can retire the other's counterpart without touching it, so collapsing them here would
     * silently discard whichever lever you dropped. A false bit FAILS CLOSED (anti-downgrade, §8.4).
     *
     * The signed manifest carries no lifecycle bit, so a manifest-only (offline) resolution assumes
     * `true` for both; the authoritative values are the two on-chain `active` members when online — see
     * `anchor_from_manifest` / `anchor_from_reconciliation` on the server side.
     */
    public var contractSetActive: Bool
    /**
     * The ARTIFACT axis's lifecycle bit — `ArtifactSet.active`, as read from
     * `ProtocolRegistry.getActiveArtifactSet`. `deprecateArtifactSet` flips it false.
     *
     * The independent counterpart to [`Self::contract_set_active`]: BOTH must be true for [`validate`]
     * to pass. This is the bit that lets dogtag retire a compromised proving-artifact set (a bad zkey)
     * and stop every app WITHOUT moving a single trio address. See that field's note for why the two
     * must be populated separately.
     */
    public var artifactSetActive: Bool
    /**
     * The provider-authority core (`ProviderRegistry`) this version's verification registry holds in its
     * immutable `issuerRegistry` slot — and the root of the resolver layer, since a provider's directory
     * resolver and a service's domain resolver are both selected THROUGH it.
     *
     * `None` is the honest shape of a GENERATION-1 record: `ProtocolRegistry.ContractSet` has no such
     * member, so a caller resolving that record has nothing to report and must say so rather than invent
     * an address. That is an ACCURATE OBSERVATION about the record's shape, and it is NOT a
     * could-not-check: a read that FAILED must surface as a failed resolution and must never reach
     * [`validate`] as a `None`. Generation 2's `ProtocolRegistryV2.DiscoverySet` always carries it (the
     * registry refuses to publish a zero), so a caller reading that record must populate it.
     */
    public var providerRegistry: String?
    /**
     * Whatever this version's verification registry holds in its immutable `rootIndex` slot — the
     * contract that answers `rootIssuer(bytes32)` and `isClone(address)`. In generation 2 that is the
     * `CloneProvenanceRouter`, which resolves a root across factory generations.
     *
     * This is NOT the factory. Generation 1 could conflate them because its registry's root index WAS
     * its factory; generation 2 cannot, and a consumer that reads a factory address here resolves only
     * the roots anchored in that generation while silently missing every earlier one — the exact failure
     * the router exists to prevent. `None` carries the same generation-1 meaning as
     * [`Self::provider_registry`].
     */
    public var rootIndex: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The version string this record certifies (e.g. `dogtag-levelb/1`).
         */version: String, 
        /**
         * keccak256(version) `0x`-hex — the on-chain `contractSetId`; ties the claimed version STRING to
         * the on-chain key so a caller cannot silently validate against the wrong record.
         */versionId: String, 
        /**
         * The ARTIFACT-AXIS identity the caller resolved for this version (e.g.
         * `dogtag-levelb-artifacts/1`) — the artifact set `activeArtifactSetOf[versionId]` points at.
         *
         * It is a SECOND, independent axis (R-5): rotating the proving artifacts changes this and
         * `min_app_version` while `version`/`version_id` and `verification_registry` stay put. Carrying it
         * on the anchor is what lets a caller say WHICH artifact set it is about to fetch, rather than
         * inferring it from the version.
         */artifactSet: String, 
        /**
         * keccak256(artifact_set) `0x`-hex — the on-chain `artifactSetId`. A DIFFERENT keyspace from
         * `version_id`; [`validate`] checks their coherence independently.
         */artifactSetId: String, 
        /**
         * The chain the trio lives on. (Carried by the manifest / known by the app from its RPC endpoint;
         * the on-chain `ContractSet` struct itself has no chain-id member — the registry IS on a chain.)
         */chainId: UInt64, 
        /**
         * The registry a proof is submitted to (trio leg). The anti-redirect anchor.
         */verificationRegistry: String, 
        /**
         * The circuit this version proves (`<source>/<template>(<params>)`) — the artifact-selection key
         * (§5.3 step 6; version↔circuit_id is 1:1 in `dogtag_prover::artifact`).
         */circuitId: String, 
        /**
         * Minimum app build (semver) allowed to use this version — the deprecation lever (§5.3 step 5).
         */minAppVersion: String, 
        /**
         * The ON-CHAIN axis's lifecycle bit — `ContractSet.active`, as read from
         * `ProtocolRegistry.getContractSet`. `deprecateContractSet` flips it false.
         *
         * It is an INDEPENDENT kill switch, and [`validate`] requires BOTH it and
         * [`Self::artifact_set_active`] to be true. Populate the two SEPARATELY from the two on-chain
         * records — never AND them into one field and never wire only one: R-5 splits the axes precisely so
         * each can retire the other's counterpart without touching it, so collapsing them here would
         * silently discard whichever lever you dropped. A false bit FAILS CLOSED (anti-downgrade, §8.4).
         *
         * The signed manifest carries no lifecycle bit, so a manifest-only (offline) resolution assumes
         * `true` for both; the authoritative values are the two on-chain `active` members when online — see
         * `anchor_from_manifest` / `anchor_from_reconciliation` on the server side.
         */contractSetActive: Bool, 
        /**
         * The ARTIFACT axis's lifecycle bit — `ArtifactSet.active`, as read from
         * `ProtocolRegistry.getActiveArtifactSet`. `deprecateArtifactSet` flips it false.
         *
         * The independent counterpart to [`Self::contract_set_active`]: BOTH must be true for [`validate`]
         * to pass. This is the bit that lets dogtag retire a compromised proving-artifact set (a bad zkey)
         * and stop every app WITHOUT moving a single trio address. See that field's note for why the two
         * must be populated separately.
         */artifactSetActive: Bool, 
        /**
         * The provider-authority core (`ProviderRegistry`) this version's verification registry holds in its
         * immutable `issuerRegistry` slot — and the root of the resolver layer, since a provider's directory
         * resolver and a service's domain resolver are both selected THROUGH it.
         *
         * `None` is the honest shape of a GENERATION-1 record: `ProtocolRegistry.ContractSet` has no such
         * member, so a caller resolving that record has nothing to report and must say so rather than invent
         * an address. That is an ACCURATE OBSERVATION about the record's shape, and it is NOT a
         * could-not-check: a read that FAILED must surface as a failed resolution and must never reach
         * [`validate`] as a `None`. Generation 2's `ProtocolRegistryV2.DiscoverySet` always carries it (the
         * registry refuses to publish a zero), so a caller reading that record must populate it.
         */providerRegistry: String?, 
        /**
         * Whatever this version's verification registry holds in its immutable `rootIndex` slot — the
         * contract that answers `rootIssuer(bytes32)` and `isClone(address)`. In generation 2 that is the
         * `CloneProvenanceRouter`, which resolves a root across factory generations.
         *
         * This is NOT the factory. Generation 1 could conflate them because its registry's root index WAS
         * its factory; generation 2 cannot, and a consumer that reads a factory address here resolves only
         * the roots anchored in that generation while silently missing every earlier one — the exact failure
         * the router exists to prevent. `None` carries the same generation-1 meaning as
         * [`Self::provider_registry`].
         */rootIndex: String?) {
        self.version = version
        self.versionId = versionId
        self.artifactSet = artifactSet
        self.artifactSetId = artifactSetId
        self.chainId = chainId
        self.verificationRegistry = verificationRegistry
        self.circuitId = circuitId
        self.minAppVersion = minAppVersion
        self.contractSetActive = contractSetActive
        self.artifactSetActive = artifactSetActive
        self.providerRegistry = providerRegistry
        self.rootIndex = rootIndex
    }
}



extension TrustedAnchor: Equatable, Hashable {
    public static func ==(lhs: TrustedAnchor, rhs: TrustedAnchor) -> Bool {
        if lhs.version != rhs.version {
            return false
        }
        if lhs.versionId != rhs.versionId {
            return false
        }
        if lhs.artifactSet != rhs.artifactSet {
            return false
        }
        if lhs.artifactSetId != rhs.artifactSetId {
            return false
        }
        if lhs.chainId != rhs.chainId {
            return false
        }
        if lhs.verificationRegistry != rhs.verificationRegistry {
            return false
        }
        if lhs.circuitId != rhs.circuitId {
            return false
        }
        if lhs.minAppVersion != rhs.minAppVersion {
            return false
        }
        if lhs.contractSetActive != rhs.contractSetActive {
            return false
        }
        if lhs.artifactSetActive != rhs.artifactSetActive {
            return false
        }
        if lhs.providerRegistry != rhs.providerRegistry {
            return false
        }
        if lhs.rootIndex != rhs.rootIndex {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(version)
        hasher.combine(versionId)
        hasher.combine(artifactSet)
        hasher.combine(artifactSetId)
        hasher.combine(chainId)
        hasher.combine(verificationRegistry)
        hasher.combine(circuitId)
        hasher.combine(minAppVersion)
        hasher.combine(contractSetActive)
        hasher.combine(artifactSetActive)
        hasher.combine(providerRegistry)
        hasher.combine(rootIndex)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTrustedAnchor: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TrustedAnchor {
        return
            try TrustedAnchor(
                version: FfiConverterString.read(from: &buf), 
                versionId: FfiConverterString.read(from: &buf), 
                artifactSet: FfiConverterString.read(from: &buf), 
                artifactSetId: FfiConverterString.read(from: &buf), 
                chainId: FfiConverterUInt64.read(from: &buf), 
                verificationRegistry: FfiConverterString.read(from: &buf), 
                circuitId: FfiConverterString.read(from: &buf), 
                minAppVersion: FfiConverterString.read(from: &buf), 
                contractSetActive: FfiConverterBool.read(from: &buf), 
                artifactSetActive: FfiConverterBool.read(from: &buf), 
                providerRegistry: FfiConverterOptionString.read(from: &buf), 
                rootIndex: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: TrustedAnchor, into buf: inout [UInt8]) {
        FfiConverterString.write(value.version, into: &buf)
        FfiConverterString.write(value.versionId, into: &buf)
        FfiConverterString.write(value.artifactSet, into: &buf)
        FfiConverterString.write(value.artifactSetId, into: &buf)
        FfiConverterUInt64.write(value.chainId, into: &buf)
        FfiConverterString.write(value.verificationRegistry, into: &buf)
        FfiConverterString.write(value.circuitId, into: &buf)
        FfiConverterString.write(value.minAppVersion, into: &buf)
        FfiConverterBool.write(value.contractSetActive, into: &buf)
        FfiConverterBool.write(value.artifactSetActive, into: &buf)
        FfiConverterOptionString.write(value.providerRegistry, into: &buf)
        FfiConverterOptionString.write(value.rootIndex, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTrustedAnchor_lift(_ buf: RustBuffer) throws -> TrustedAnchor {
    return try FfiConverterTypeTrustedAnchor.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTrustedAnchor_lower(_ value: TrustedAnchor) -> RustBuffer {
    return FfiConverterTypeTrustedAnchor.lower(value)
}


/**
 * The result of a PASSING validation (§5.3): the version + its artifact-selection key + the
 * authoritative trust-critical fields the caller may now act on. The caller selects the proving
 * artifact by `version`/`circuit_id` (§5.3 step 6): `dogtag_prover::artifact::resolve(Some(&version))`
 * yields the descriptor, whose `circuit_id` MUST equal this.
 */
public struct ValidatedVersion {
    public var version: String
    public var circuitId: String
    public var chainId: UInt64
    public var verificationRegistry: String
    /**
     * The validated ARTIFACT-AXIS identity (R-5) — which proving-artifact set the caller may now
     * fetch. Returned separately from `version` precisely because it moves separately: an artifact
     * rotation changes this while `version`/`circuit_id`/`verification_registry` are unchanged.
     */
    public var artifactSet: String
    /**
     * The validated provider-authority core, or `None` when the resolved record does not carry one.
     * Returned so a caller acts on the value this function checked rather than re-reading the anchor —
     * the same reason `verification_registry` is returned.
     */
    public var providerRegistry: String?
    /**
     * The validated root index (generation 2's `CloneProvenanceRouter`), or `None` when the resolved
     * record does not carry one. A caller reading `rootIssuer`/`isClone` MUST use this rather than a
     * bundled factory address; see [`TrustedAnchor::root_index`].
     */
    public var rootIndex: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(version: String, circuitId: String, chainId: UInt64, verificationRegistry: String, 
        /**
         * The validated ARTIFACT-AXIS identity (R-5) — which proving-artifact set the caller may now
         * fetch. Returned separately from `version` precisely because it moves separately: an artifact
         * rotation changes this while `version`/`circuit_id`/`verification_registry` are unchanged.
         */artifactSet: String, 
        /**
         * The validated provider-authority core, or `None` when the resolved record does not carry one.
         * Returned so a caller acts on the value this function checked rather than re-reading the anchor —
         * the same reason `verification_registry` is returned.
         */providerRegistry: String?, 
        /**
         * The validated root index (generation 2's `CloneProvenanceRouter`), or `None` when the resolved
         * record does not carry one. A caller reading `rootIssuer`/`isClone` MUST use this rather than a
         * bundled factory address; see [`TrustedAnchor::root_index`].
         */rootIndex: String?) {
        self.version = version
        self.circuitId = circuitId
        self.chainId = chainId
        self.verificationRegistry = verificationRegistry
        self.artifactSet = artifactSet
        self.providerRegistry = providerRegistry
        self.rootIndex = rootIndex
    }
}



extension ValidatedVersion: Equatable, Hashable {
    public static func ==(lhs: ValidatedVersion, rhs: ValidatedVersion) -> Bool {
        if lhs.version != rhs.version {
            return false
        }
        if lhs.circuitId != rhs.circuitId {
            return false
        }
        if lhs.chainId != rhs.chainId {
            return false
        }
        if lhs.verificationRegistry != rhs.verificationRegistry {
            return false
        }
        if lhs.artifactSet != rhs.artifactSet {
            return false
        }
        if lhs.providerRegistry != rhs.providerRegistry {
            return false
        }
        if lhs.rootIndex != rhs.rootIndex {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(version)
        hasher.combine(circuitId)
        hasher.combine(chainId)
        hasher.combine(verificationRegistry)
        hasher.combine(artifactSet)
        hasher.combine(providerRegistry)
        hasher.combine(rootIndex)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeValidatedVersion: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ValidatedVersion {
        return
            try ValidatedVersion(
                version: FfiConverterString.read(from: &buf), 
                circuitId: FfiConverterString.read(from: &buf), 
                chainId: FfiConverterUInt64.read(from: &buf), 
                verificationRegistry: FfiConverterString.read(from: &buf), 
                artifactSet: FfiConverterString.read(from: &buf), 
                providerRegistry: FfiConverterOptionString.read(from: &buf), 
                rootIndex: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: ValidatedVersion, into buf: inout [UInt8]) {
        FfiConverterString.write(value.version, into: &buf)
        FfiConverterString.write(value.circuitId, into: &buf)
        FfiConverterUInt64.write(value.chainId, into: &buf)
        FfiConverterString.write(value.verificationRegistry, into: &buf)
        FfiConverterString.write(value.artifactSet, into: &buf)
        FfiConverterOptionString.write(value.providerRegistry, into: &buf)
        FfiConverterOptionString.write(value.rootIndex, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeValidatedVersion_lift(_ buf: RustBuffer) throws -> ValidatedVersion {
    return try FfiConverterTypeValidatedVersion.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeValidatedVersion_lower(_ value: ValidatedVersion) -> RustBuffer {
    return FfiConverterTypeValidatedVersion.lower(value)
}


/**
 * A single error type crossing the FFI boundary (UniFFI maps this to a thrown exception).
 */
public enum FfiError {

    
    
    case Invalid(String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiError: FfiConverterRustBuffer {
    typealias SwiftType = FfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Invalid(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Invalid(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


extension FfiError: Equatable, Hashable {}

extension FfiError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeAttributeLeafFfi: FfiConverterRustBuffer {
    typealias SwiftType = [AttributeLeafFfi]

    public static func write(_ value: [AttributeLeafFfi], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAttributeLeafFfi.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [AttributeLeafFfi] {
        let len: Int32 = try readInt(&buf)
        var seq = [AttributeLeafFfi]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeAttributeLeafFfi.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [[String]]

    public static func write(_ value: [[String]], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterSequenceString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [[String]] {
        let len: Int32 = try readInt(&buf)
        var seq = [[String]]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterSequenceString.read(from: &buf))
        }
        return seq
    }
}
/**
 * buildMerkle over a set of 0x.. 32-byte leaf hashes -> the 0x.. 32-byte root hex.
 * Sorts ascending and folds bottom-up (promote lone odd) — mirrors the SDK / TS.
 */
public func buildMerkleRootHex(leafHexes: [String])throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_build_merkle_root_hex(
        FfiConverterSequenceString.lower(leafHexes),$0
    )
})
}
/**
 * Build a `ProfileDisclosure` envelope JSON for exactly the owner-picked `reveal_key_paths`
 * (`disclosure::build_profile_disclosure`).
 *
 * Inputs mirror [`build_profile_tree_hex`] (the SAME persisted witness issuance folded), plus the
 * chosen keyPaths. The returned JSON - `{ dogTagId, R, disclosures: [{ keyPath, saltHex, tag,
 * value, proof }] }` - is the CANONICAL wire shape; embed it verbatim in the verify submission
 * verbatim in the verify submission, never hand-re-encode it. (Custodial-bind no longer uses
 * inclusion proofs: the bind posts the full attribute-leaf openings + the reserved leaf hashes
 * straight off the tree build instead.)
 *
 * Every disclosed value goes to the chosen verifier in cleartext - that is what "revealing your
 * name" means - so the callers gate this behind the owner-facing picker.
 */
public func buildProfileDisclosureJson(seedHex: String, dogTagIdHex: String, ownerAddressHex: String, attributes: [AttributeLeafFfi], revealKeyPaths: [String])throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_build_profile_disclosure_json(
        FfiConverterString.lower(seedHex),
        FfiConverterString.lower(dogTagIdHex),
        FfiConverterString.lower(ownerAddressHex),
        FfiConverterSequenceTypeAttributeLeafFfi.lower(attributes),
        FfiConverterSequenceString.lower(revealKeyPaths),$0
    )
})
}
/**
 * Build the per-tag Merkle tree ON THE DEVICE (`profile_tree::build_profile_tree`) and return `R`
 * plus the owner-private witness.
 *
 * This is spec §"Issuance" step 2: *the owner's app builds the tree locally (owner-address,
 * consent-key, owner-secret, attributes as salted leaves), computes `R`*. Hand the issuer ONLY
 * `root_hex`.
 *
 * `owner_address_hex` is the 20-byte wallet address; `dog_tag_id_hex` the canonical dogTagId field.
 */
public func buildProfileTreeHex(seedHex: String, dogTagIdHex: String, ownerAddressHex: String, attributes: [AttributeLeafFfi])throws  -> ProfileTreeFfi {
    return try  FfiConverterTypeProfileTreeFfi.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_build_profile_tree_hex(
        FfiConverterString.lower(seedHex),
        FfiConverterString.lower(dogTagIdHex),
        FfiConverterString.lower(ownerAddressHex),
        FfiConverterSequenceTypeAttributeLeafFfi.lower(attributes),$0
    )
})
}
/**
 * bytesToField: the length-prefixed, 31-byte-chunked, domain-separated Poseidon fold of raw
 * bytes (hex in) -> the 0x.. 32-byte field hex. Used for keyPath/value parity vectors.
 */
public func bytesToFieldHex(inputHex: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_bytes_to_field_hex(
        FfiConverterString.lower(inputHex),$0
    )
})
}
/**
 * Derive the owner-secret from the wallet seed, bound to `dogTagId` - the RECOVERABLE nullifier
 * secret (`profile_tree::derive_owner_secret`).
 *
 * Deterministic: restoring the seed regenerates the same secret. Rebuilding the same tree and `R`
 * additionally requires the original owner address plus the exact attribute values and salts.
 * `dog_tag_id_hex` is the canonical dogTagId field (what `dogTagIdFieldHex` returns).
 *
 * The result is owner-private and MUST NOT be transmitted: a server that learned it could link
 * nullifiers back to the owner, defeating the owner-unlinkable model.
 */
public func deriveOwnerSecretHex(seedHex: String, dogTagIdHex: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_derive_owner_secret_hex(
        FfiConverterString.lower(seedHex),
        FfiConverterString.lower(dogTagIdHex),$0
    )
})
}
/**
 * Field-hash a numeric dogTagId EXACTLY as its credential leaf value is hashed:
 * `field_of_value(Integer(dec))` -> 0x.. 32-byte hex. THE CANONICAL dogTagId: the consent circuit's
 * `dogTagId` input, the per-tag KDF binding, the Poseidon nullifier, AND the on-chain SBT id
 * (`mintCustodial(id, R)`) must ALL be this value, not the raw decimal handle.
 */
public func dogTagIdFieldHex(dogTagIdDec: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_dog_tag_id_field_hex(
        FfiConverterString.lower(dogTagIdDec),$0
    )
})
}
/**
 * hashLeaf over a single field: Poseidon(DS_LEAF, fieldOf(keyPath), fieldOf(salt),
 * fieldOf(typeTag), fieldOf(value)). `tag`+`value` are reconstructed into a TypedScalar exactly
 * like `wrap::scalar_from_packed` does (the same path verify uses). Returns 0x.. 32-byte hex.
 */
public func hashLeafHex(keyPath: String, saltHex: String, tag: UInt8, value: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_hash_leaf_hex(
        FfiConverterString.lower(keyPath),
        FfiConverterString.lower(saltHex),
        FfiConverterUInt8.lower(tag),
        FfiConverterString.lower(value),$0
    )
})
}
/**
 * hashNode: the commutative internal-node hash `Poseidon3(DS_NODE, min(a,b), max(a,b))` over two
 * 0x.. 32-byte field hexes -> the 0x.. 32-byte node hex. The primitive a foreign `Sibling | Promote`
 * inclusion verifier folds with (Swift/Kotlin) so the Poseidon parameter set stays pinned in Rust.
 */
public func hashNodeHex(aHex: String, bHex: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_hash_node_hex(
        FfiConverterString.lower(aHex),
        FfiConverterString.lower(bHex),$0
    )
})
}
/**
 * NFC-normalize a string (exposed for cross-language canonicalization sanity checks).
 */
public func nfcNormalize(input: String) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_dogtag_standard_fn_func_nfc_normalize(
        FfiConverterString.lower(input),$0
    )
})
}
/**
 * obfuscate — the merkle selective-disclosure primitive (mirror `wrap::obfuscate`). Moves each
 * named field's leaf hash into `privacy.obfuscated[]` and drops its cleartext, leaving the Merkle
 * root (== the on-chain root R) UNCHANGED. This is what lets the phone produce a PII-free
 * presentation copy LOCALLY: the holder hides Section-A person-PII leaves while the tree still
 * rebuilds to R, so every disclosed (Section B/C/validity/receiptId) leaf stays verifiable on-chain.
 *
 * `key_paths` are dotted leaf key-paths as they appear in `data` (e.g.
 * `credentialSubject.importer.idNumber`). `credentialSubject.dogTagId` is the one leaf that must
 * never be obfuscated (`verify.rs` rejects it as the non-obfuscatable SBT binding); obfuscating a
 * missing key errors. Returns the redacted WrappedDoc JSON, which `verify_integrity` still passes.
 */
public func obfuscateDocumentJson(wrappedDocJson: String, keyPaths: [String])throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_obfuscate_document_json(
        FfiConverterString.lower(wrappedDocJson),
        FfiConverterSequenceString.lower(keyPaths),$0
    )
})
}
/**
 * Generate a Groth16 proof for the DogTag CONSENT circuit (`consent.circom`, `DogTagConsent(6)`) ON
 * DEVICE (M7 P0).
 *
 * Uses the `circom-witnesscalc` GRAPH backend (deliberately not rust-witness/wasm2c, which
 * miscompiles i64 field math on 32-bit ARM) for the owner-unlinkable consent circuit: it ASSEMBLES
 * the inputs with [`assemble_consent`] (the canonical `dogTagId` field is computed once and used
 * for both the circuit input and the `build_profile_tree` KDF binding), then proves.
 *
 * - `seed_hex`            — the owner wallet seed (0x..); owner-secret/consent-key/salts derive from it.
 * - `dog_tag_id_handle`   — the off-chain decimal handle; field-hashed to the canonical `dogTagId`.
 * - `owner_address_hex`   — 0x.. 20-byte owner address (the owner-address reserved leaf value).
 * - `attributes_json`     — the disclosable credential attributes (see [`parse_attributes`]); MUST
 * match issuance so the rebuilt `R` equals the minted `profileRoot`.
 * - `purpose_hex` / `record_type_hex` / `consent_nonce_hex` — 0x.. 32-byte field words.
 * - `relayer_hex`         — 0x.. 20-byte relayer address (range-checked `< 2^160` by the circuit).
 * - `deadline_dec`        — the consent expiry as a decimal string.
 * - `zkey_path` / `graph_path` — `consent_final.zkey` + `consent.graph` (bundled/fetched app assets).
 *
 * Returns the proof as Solidity calldata plus the 7 public signals in the FROZEN OUTPUT order
 * `[dogTagId, purpose, relayer, nullifier, R, recordType, deadline]` (all decimal).
 */
public func proveConsent(seedHex: String, dogTagIdHandle: String, ownerAddressHex: String, attributesJson: String, purposeHex: String, relayerHex: String, recordTypeHex: String, consentNonceHex: String, deadlineDec: String, zkeyPath: String, graphPath: String)throws  -> ProofFfi {
    return try  FfiConverterTypeProofFfi.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_prove_consent(
        FfiConverterString.lower(seedHex),
        FfiConverterString.lower(dogTagIdHandle),
        FfiConverterString.lower(ownerAddressHex),
        FfiConverterString.lower(attributesJson),
        FfiConverterString.lower(purposeHex),
        FfiConverterString.lower(relayerHex),
        FfiConverterString.lower(recordTypeHex),
        FfiConverterString.lower(consentNonceHex),
        FfiConverterString.lower(deadlineDec),
        FfiConverterString.lower(zkeyPath),
        FfiConverterString.lower(graphPath),$0
    )
})
}
/**
 * Thin UniFFI surface so the mobile app's resolve→validate step can call the same pure validator the
 * server uses (§5.3). Takes the two `ClientContext` strings directly (the borrow struct cannot cross
 * the boundary) and flattens [`DiscoveryError`] into the crate's single [`crate::ffi::FfiError`].
 */
public func validateDiscovery(claims: ConvenienceClaims, anchor: TrustedAnchor, appVersion: String, expectedPurpose: String)throws  -> ValidatedVersion {
    return try  FfiConverterTypeValidatedVersion.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_validate_discovery(
        FfiConverterTypeConvenienceClaims.lower(claims),
        FfiConverterTypeTrustedAnchor.lower(anchor),
        FfiConverterString.lower(appVersion),
        FfiConverterString.lower(expectedPurpose),$0
    )
})
}
/**
 * verifyInclusionProof: the NORMATIVE DSDP §2.3 disclosed-leaf check over the FFI boundary.
 *
 * RECOMPUTES the leaf hash from `(key_path, salt, tag, value)` under `DS_LEAF` (Poseidon5) — never
 * trusting a supplied leaf hash — then folds the root-ward `Sibling | Promote` proof and returns
 * whether it equals `root_hex`. `proof_steps` encodes each step as either the literal `"promote"`
 * (a lone-odd-node pass-through) or a 0x.. 32-byte sibling hex. This is the canonical reference the
 * foreign verifiers cross-check against (their own fold via [`hash_leaf_hex`] + [`hash_node_hex`]
 * must agree with this).
 */
public func verifyInclusionProofHex(keyPath: String, saltHex: String, tag: UInt8, value: String, proofSteps: [String], rootHex: String)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_verify_inclusion_proof_hex(
        FfiConverterString.lower(keyPath),
        FfiConverterString.lower(saltHex),
        FfiConverterUInt8.lower(tag),
        FfiConverterString.lower(value),
        FfiConverterSequenceString.lower(proofSteps),
        FfiConverterString.lower(rootHex),$0
    )
})
}
/**
 * The pure §11.3 integrity pillar over a WrappedDoc JSON: rebuild the whole tree and compare to
 * targetHash/merkleRoot. This is what mobile runs OFFLINE. Returns "VALID" / "INVALID".
 */
public func verifyIntegrity(wrappedDocJson: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_verify_integrity(
        FfiConverterString.lower(wrappedDocJson),$0
    )
})
}
/**
 * Verify the PURE half of a `ProfileDisclosure` envelope JSON
 * (`disclosure::verify_profile_disclosure`): every entry's leaf is RECOMPUTED from its
 * `(keyPath, salt, tag, value)` opening under `DS_LEAF` - a caller-supplied hash is never
 * trusted - and must fold through its proof to the envelope's `R`.
 *
 * Callers must ADDITIONALLY bind the envelope on-chain (`R == profileRoot(dogTagId)`,
 * `rootIssuer[R]`/`isValid(R)`) and to the consent proof it rides alongside.
 */
public func verifyProfileDisclosureJson(disclosureJson: String)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_verify_profile_disclosure_json(
        FfiConverterString.lower(disclosureJson),$0
    )
})
}
/**
 * The IssuerRegistry whitelist key the VerificationRegistry checks for the relayer on a given
 * purpose label: `keccak256(abi.encode("VERIFY:", purpose_key(label)))` as `0x..` hex.
 *
 * Used by the mobile pre-proof check (`IssuerRegistry.isWhitelistedFor(key, relayer)`). Available
 * even without the `prover` feature. Byte-for-byte parity with backend `verify.rs::verify_key`.
 */
public func verifyWhitelistKeyHex(purposeLabel: String) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_dogtag_standard_fn_func_verify_whitelist_key_hex(
        FfiConverterString.lower(purposeLabel),$0
    )
})
}
/**
 * wrapDocument — typed credential JSON + issuer JSON -> WrappedDoc JSON. Salts come from the OS
 * RNG (each leaf gets 16 fresh bytes). Mirrors `wrap::wrap_document`.
 */
public func wrapDocumentJson(typedCredentialJson: String, issuerJson: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_wrap_document_json(
        FfiConverterString.lower(typedCredentialJson),
        FfiConverterString.lower(issuerJson),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_dogtag_standard_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_build_merkle_root_hex() != 1024) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_build_profile_disclosure_json() != 39777) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_build_profile_tree_hex() != 20561) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_bytes_to_field_hex() != 34986) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_derive_owner_secret_hex() != 61221) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_dog_tag_id_field_hex() != 48168) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_hash_leaf_hex() != 23706) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_hash_node_hex() != 61695) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_nfc_normalize() != 7804) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_obfuscate_document_json() != 27517) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_prove_consent() != 24480) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_validate_discovery() != 58309) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_verify_inclusion_proof_hex() != 37971) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_verify_integrity() != 1032) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_verify_profile_disclosure_json() != 42990) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_verify_whitelist_key_hex() != 28611) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_wrap_document_json() != 24325) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all