// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(dogtag_standardFFI)
import dogtag_standardFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_dogtag_standard_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_dogtag_standard_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


/**
 * A derived BabyJubjub consent keypair crossing the FFI boundary. `prvHex` is the 32-byte private
 * key (keep encrypted behind the platform keystore); Ax/Ay are 0x.. 32-byte BE public-point hex;
 * keyHashHex = Poseidon(Ax,Ay) is what the wallet binds in ConsentKeyRegistry.
 */
public struct BabyjubConsentKeyFfi {
    public var prvHex: String
    public var axHex: String
    public var ayHex: String
    public var keyHashHex: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(prvHex: String, axHex: String, ayHex: String, keyHashHex: String) {
        self.prvHex = prvHex
        self.axHex = axHex
        self.ayHex = ayHex
        self.keyHashHex = keyHashHex
    }
}



extension BabyjubConsentKeyFfi: Equatable, Hashable {
    public static func ==(lhs: BabyjubConsentKeyFfi, rhs: BabyjubConsentKeyFfi) -> Bool {
        if lhs.prvHex != rhs.prvHex {
            return false
        }
        if lhs.axHex != rhs.axHex {
            return false
        }
        if lhs.ayHex != rhs.ayHex {
            return false
        }
        if lhs.keyHashHex != rhs.keyHashHex {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(prvHex)
        hasher.combine(axHex)
        hasher.combine(ayHex)
        hasher.combine(keyHashHex)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBabyjubConsentKeyFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BabyjubConsentKeyFfi {
        return
            try BabyjubConsentKeyFfi(
                prvHex: FfiConverterString.read(from: &buf), 
                axHex: FfiConverterString.read(from: &buf), 
                ayHex: FfiConverterString.read(from: &buf), 
                keyHashHex: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: BabyjubConsentKeyFfi, into buf: inout [UInt8]) {
        FfiConverterString.write(value.prvHex, into: &buf)
        FfiConverterString.write(value.axHex, into: &buf)
        FfiConverterString.write(value.ayHex, into: &buf)
        FfiConverterString.write(value.keyHashHex, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBabyjubConsentKeyFfi_lift(_ buf: RustBuffer) throws -> BabyjubConsentKeyFfi {
    return try FfiConverterTypeBabyjubConsentKeyFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBabyjubConsentKeyFfi_lower(_ value: BabyjubConsentKeyFfi) -> RustBuffer {
    return FfiConverterTypeBabyjubConsentKeyFfi.lower(value)
}


/**
 * The pass-through EdDSA-BabyJubjub consent signature + public key (decimal scalars + hex point).
 *
 * `r8x_dec` / `r8y_dec` / `s_dec` come from `sign_consent_eddsa` (ffi.rs `EddsaSignatureFfi`);
 * `ax_hex` / `ay_hex` are the consent public point (0x.. 32-byte BE field hex).
 */
public struct EddsaSigInput {
    public var r8xDec: String
    public var r8yDec: String
    public var sDec: String
    public var axHex: String
    public var ayHex: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(r8xDec: String, r8yDec: String, sDec: String, axHex: String, ayHex: String) {
        self.r8xDec = r8xDec
        self.r8yDec = r8yDec
        self.sDec = sDec
        self.axHex = axHex
        self.ayHex = ayHex
    }
}



extension EddsaSigInput: Equatable, Hashable {
    public static func ==(lhs: EddsaSigInput, rhs: EddsaSigInput) -> Bool {
        if lhs.r8xDec != rhs.r8xDec {
            return false
        }
        if lhs.r8yDec != rhs.r8yDec {
            return false
        }
        if lhs.sDec != rhs.sDec {
            return false
        }
        if lhs.axHex != rhs.axHex {
            return false
        }
        if lhs.ayHex != rhs.ayHex {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(r8xDec)
        hasher.combine(r8yDec)
        hasher.combine(sDec)
        hasher.combine(axHex)
        hasher.combine(ayHex)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEddsaSigInput: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EddsaSigInput {
        return
            try EddsaSigInput(
                r8xDec: FfiConverterString.read(from: &buf), 
                r8yDec: FfiConverterString.read(from: &buf), 
                sDec: FfiConverterString.read(from: &buf), 
                axHex: FfiConverterString.read(from: &buf), 
                ayHex: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: EddsaSigInput, into buf: inout [UInt8]) {
        FfiConverterString.write(value.r8xDec, into: &buf)
        FfiConverterString.write(value.r8yDec, into: &buf)
        FfiConverterString.write(value.sDec, into: &buf)
        FfiConverterString.write(value.axHex, into: &buf)
        FfiConverterString.write(value.ayHex, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEddsaSigInput_lift(_ buf: RustBuffer) throws -> EddsaSigInput {
    return try FfiConverterTypeEddsaSigInput.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEddsaSigInput_lower(_ value: EddsaSigInput) -> RustBuffer {
    return FfiConverterTypeEddsaSigInput.lower(value)
}


/**
 * An EdDSA-BabyJubjub Poseidon consent signature: R8 point (0x.. 32-byte hex) + scalar S (decimal).
 */
public struct EddsaSignatureFfi {
    public var r8xHex: String
    public var r8yHex: String
    public var r8xDec: String
    public var r8yDec: String
    public var sDec: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(r8xHex: String, r8yHex: String, r8xDec: String, r8yDec: String, sDec: String) {
        self.r8xHex = r8xHex
        self.r8yHex = r8yHex
        self.r8xDec = r8xDec
        self.r8yDec = r8yDec
        self.sDec = sDec
    }
}



extension EddsaSignatureFfi: Equatable, Hashable {
    public static func ==(lhs: EddsaSignatureFfi, rhs: EddsaSignatureFfi) -> Bool {
        if lhs.r8xHex != rhs.r8xHex {
            return false
        }
        if lhs.r8yHex != rhs.r8yHex {
            return false
        }
        if lhs.r8xDec != rhs.r8xDec {
            return false
        }
        if lhs.r8yDec != rhs.r8yDec {
            return false
        }
        if lhs.sDec != rhs.sDec {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(r8xHex)
        hasher.combine(r8yHex)
        hasher.combine(r8xDec)
        hasher.combine(r8yDec)
        hasher.combine(sDec)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEddsaSignatureFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EddsaSignatureFfi {
        return
            try EddsaSignatureFfi(
                r8xHex: FfiConverterString.read(from: &buf), 
                r8yHex: FfiConverterString.read(from: &buf), 
                r8xDec: FfiConverterString.read(from: &buf), 
                r8yDec: FfiConverterString.read(from: &buf), 
                sDec: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: EddsaSignatureFfi, into buf: inout [UInt8]) {
        FfiConverterString.write(value.r8xHex, into: &buf)
        FfiConverterString.write(value.r8yHex, into: &buf)
        FfiConverterString.write(value.r8xDec, into: &buf)
        FfiConverterString.write(value.r8yDec, into: &buf)
        FfiConverterString.write(value.sDec, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEddsaSignatureFfi_lift(_ buf: RustBuffer) throws -> EddsaSignatureFfi {
    return try FfiConverterTypeEddsaSignatureFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEddsaSignatureFfi_lower(_ value: EddsaSignatureFfi) -> RustBuffer {
    return FfiConverterTypeEddsaSignatureFfi.lower(value)
}


/**
 * A Groth16 proof formatted exactly as the on-chain Solidity calldata expects (mirrors
 * `dogtag-prover-rs::Groth16Output`): `a`/`c` are G1 `[x,y]`; `b` is G2 with the snarkjs->Solidity
 * coordinate swap applied (`b[0]=[bx_c1,bx_c0]`, `b[1]=[by_c1,by_c0]`); `pub_signals` is the
 * 7-element output vector. All values are base-10 decimal strings.
 */
public struct ProofFfi {
    public var a: [String]
    public var b: [[String]]
    public var c: [String]
    public var pubSignals: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(a: [String], b: [[String]], c: [String], pubSignals: [String]) {
        self.a = a
        self.b = b
        self.c = c
        self.pubSignals = pubSignals
    }
}



extension ProofFfi: Equatable, Hashable {
    public static func ==(lhs: ProofFfi, rhs: ProofFfi) -> Bool {
        if lhs.a != rhs.a {
            return false
        }
        if lhs.b != rhs.b {
            return false
        }
        if lhs.c != rhs.c {
            return false
        }
        if lhs.pubSignals != rhs.pubSignals {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(a)
        hasher.combine(b)
        hasher.combine(c)
        hasher.combine(pubSignals)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProofFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProofFfi {
        return
            try ProofFfi(
                a: FfiConverterSequenceString.read(from: &buf), 
                b: FfiConverterSequenceSequenceString.read(from: &buf), 
                c: FfiConverterSequenceString.read(from: &buf), 
                pubSignals: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: ProofFfi, into buf: inout [UInt8]) {
        FfiConverterSequenceString.write(value.a, into: &buf)
        FfiConverterSequenceSequenceString.write(value.b, into: &buf)
        FfiConverterSequenceString.write(value.c, into: &buf)
        FfiConverterSequenceString.write(value.pubSignals, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProofFfi_lift(_ buf: RustBuffer) throws -> ProofFfi {
    return try FfiConverterTypeProofFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProofFfi_lower(_ value: ProofFfi) -> RustBuffer {
    return FfiConverterTypeProofFfi.lower(value)
}


/**
 * A single error type crossing the FFI boundary (UniFFI maps this to a thrown exception).
 */
public enum FfiError {

    
    
    case Invalid(String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiError: FfiConverterRustBuffer {
    typealias SwiftType = FfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Invalid(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Invalid(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


extension FfiError: Equatable, Hashable {}

extension FfiError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [[String]]

    public static func write(_ value: [[String]], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterSequenceString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [[String]] {
        let len: Int32 = try readInt(&buf)
        var seq = [[String]]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterSequenceString.read(from: &buf))
        }
        return seq
    }
}
/**
 * Build a consent key directly from a 32-byte circomlibjs private key (the raw private buffer is
 * the key — no domain wrapping). For interop with vectors / externally-derived keys.
 */
public func babyjubConsentKeyFromPrv(prvHex: String)throws  -> BabyjubConsentKeyFfi {
    return try  FfiConverterTypeBabyjubConsentKeyFfi.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_babyjub_consent_key_from_prv(
        FfiConverterString.lower(prvHex),$0
    )
})
}
/**
 * The EIP-712 digest the owner's secp256k1 wallet signs to authorize a relayer-sponsored
 * consent-key bind (`ConsentKeyRegistry.bindConsentKeyFor`). Returns 0x.. 32-byte hex of
 * keccak256(0x1901 || domainSeparator("DogTag","1",chainId,consentKeyRegistry) ||
 * keccak256(abi.encode(BIND_TYPEHASH, keyHash, wallet, nonce))). NOT feature-gated — mobile
 * needs it regardless of the `prover` feature. `nonce` is `bindNonce[wallet]` (a uint256 < 2^64
 * in practice; passed as u64 and BE-padded to 32 bytes).
 */
public func bindConsentKeyDigestHex(consentKeyRegistryAddr: String, keyHashHex: String, walletAddr: String, nonce: UInt64, chainId: UInt64)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_bind_consent_key_digest_hex(
        FfiConverterString.lower(consentKeyRegistryAddr),
        FfiConverterString.lower(keyHashHex),
        FfiConverterString.lower(walletAddr),
        FfiConverterUInt64.lower(nonce),
        FfiConverterUInt64.lower(chainId),$0
    )
})
}
/**
 * buildMerkle over a set of 0x.. 32-byte leaf hashes -> the 0x.. 32-byte root hex.
 * Sorts ascending and folds bottom-up (promote lone odd) — mirrors the SDK / TS.
 */
public func buildMerkleRootHex(leafHexes: [String])throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_build_merkle_root_hex(
        FfiConverterSequenceString.lower(leafHexes),$0
    )
})
}
/**
 * bytesToField: the length-prefixed, 31-byte-chunked, domain-separated Poseidon fold of raw
 * bytes (hex in) -> the 0x.. 32-byte field hex. Used for keyPath/value parity vectors.
 */
public func bytesToFieldHex(inputHex: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_bytes_to_field_hex(
        FfiConverterString.lower(inputHex),$0
    )
})
}
/**
 * The consent nullifier (impl §11.9(b)): Poseidon(DS_NULLIFIER, dogTagId, purpose, relayer,
 * subject, nonce) -> 0x.. 32-byte hex.
 */
public func consentNullifierHex(dogTagIdHex: String, recordTypeHex: String, purposeHex: String, credentialRootHex: String, challengeHex: String, relayerHex: String, subjectHex: String, nonceHex: String, deadlineHex: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_consent_nullifier_hex(
        FfiConverterString.lower(dogTagIdHex),
        FfiConverterString.lower(recordTypeHex),
        FfiConverterString.lower(purposeHex),
        FfiConverterString.lower(credentialRootHex),
        FfiConverterString.lower(challengeHex),
        FfiConverterString.lower(relayerHex),
        FfiConverterString.lower(subjectHex),
        FfiConverterString.lower(nonceHex),
        FfiConverterString.lower(deadlineHex),$0
    )
})
}
/**
 * Derive a deterministic BabyJubjub consent key from a hex seed (any length). The seed is wrapped
 * in a distinct domain from the secp256k1 wallet path (§6) before BLAKE-512, so the two keys are
 * independent. Returns the 32-byte private key + public point (Ax, Ay) + keyHash.
 */
public func deriveBabyjubConsentKey(seedHex: String)throws  -> BabyjubConsentKeyFfi {
    return try  FfiConverterTypeBabyjubConsentKeyFfi.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_derive_babyjub_consent_key(
        FfiConverterString.lower(seedHex),$0
    )
})
}
/**
 * Field-hash a numeric dogTagId EXACTLY as its credential leaf value is hashed:
 * `field_of_value(Integer(dec))` -> 0x.. 32-byte hex. THE CANONICAL dogTagId: the §1.10 consent's
 * dogTagId, the EdDSA consent message M, the Poseidon nullifier, AND the on-chain DOG_PROFILE SBT id
 * must ALL be this value — it equals `leafValues[dogTagIdLeafIndex]`, which the verification circuit
 * compares to the dogTagId input DIRECTLY (constraint §(b)), not the raw decimal id.
 */
public func dogTagIdFieldHex(dogTagIdDec: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_dog_tag_id_field_hex(
        FfiConverterString.lower(dogTagIdDec),$0
    )
})
}
/**
 * The EdDSA-BabyJubjub consent message M (impl §11.9(d)): Poseidon(dogTagId, purpose, relayer,
 * subject, credentialRoot, nonce) -> 0x.. 32-byte hex.
 */
public func eddsaConsentMessageHex(dogTagIdHex: String, recordTypeHex: String, purposeHex: String, credentialRootHex: String, challengeHex: String, relayerHex: String, subjectHex: String, nonceHex: String, deadlineHex: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_eddsa_consent_message_hex(
        FfiConverterString.lower(dogTagIdHex),
        FfiConverterString.lower(recordTypeHex),
        FfiConverterString.lower(purposeHex),
        FfiConverterString.lower(credentialRootHex),
        FfiConverterString.lower(challengeHex),
        FfiConverterString.lower(relayerHex),
        FfiConverterString.lower(subjectHex),
        FfiConverterString.lower(nonceHex),
        FfiConverterString.lower(deadlineHex),$0
    )
})
}
/**
 * hashLeaf over a single field: Poseidon(DS_LEAF, fieldOf(keyPath), fieldOf(salt),
 * fieldOf(typeTag), fieldOf(value)). `tag`+`value` are reconstructed into a TypedScalar exactly
 * like `wrap::scalar_from_packed` does (the same path verify uses). Returns 0x.. 32-byte hex.
 */
public func hashLeafHex(keyPath: String, saltHex: String, tag: UInt8, value: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_hash_leaf_hex(
        FfiConverterString.lower(keyPath),
        FfiConverterString.lower(saltHex),
        FfiConverterUInt8.lower(tag),
        FfiConverterString.lower(value),$0
    )
})
}
/**
 * keyHash = Poseidon(Ax, Ay) -> 0x.. 32-byte hex. Ax/Ay are 0x.. 32-byte BE field hex.
 */
public func keyHashHex(axHex: String, ayHex: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_key_hash_hex(
        FfiConverterString.lower(axHex),
        FfiConverterString.lower(ayHex),$0
    )
})
}
/**
 * NFC-normalize a string (exposed for cross-language canonicalization sanity checks).
 */
public func nfcNormalize(input: String) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_dogtag_standard_fn_func_nfc_normalize(
        FfiConverterString.lower(input),$0
    )
})
}
/**
 * Generate a Groth16 proof for the DogTag verification circuit ON DEVICE.
 *
 * - `wrapped_doc_json` — the stored WrappedDoc (raw salted leaves; the witness source).
 * - `consent_json`     — the signed consent (same hex shape as the POSTed consent / ffi.rs consent).
 * - `eddsa_sig`        — the EdDSA-BabyJubjub consent signature + public key.
 * - `zkey_path`        — filesystem path to `verification_final.zkey` (bundled app asset).
 * - `graph_path`       — filesystem path to `verification.graph`, the precompiled witness graph
 * (bundled app asset, loaded the same way as the zkey).
 *
 * Returns the proof as Solidity calldata (`a`, `b` with the snarkjs->Solidity swap, `c`) plus the
 * 7 public signals `[dogTagId, purpose, relayer, subject, nullifier, keyHash, R]` (all decimal).
 */
public func proveVerification(wrappedDocJson: String, consentJson: String, eddsaSig: EddsaSigInput, zkeyPath: String, graphPath: String)throws  -> ProofFfi {
    return try  FfiConverterTypeProofFfi.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_prove_verification(
        FfiConverterString.lower(wrappedDocJson),
        FfiConverterString.lower(consentJson),
        FfiConverterTypeEddsaSigInput.lower(eddsaSig),
        FfiConverterString.lower(zkeyPath),
        FfiConverterString.lower(graphPath),$0
    )
})
}
/**
 * Sign the §1.10 consent message M = Poseidon6(dogTagId, purpose, relayer, subject, credentialRoot,
 * nonce) with a 32-byte private key, producing the EdDSA-BabyJubjub Poseidon signature the ZK
 * circuit's `EdDSAPoseidonVerifier` accepts. Consent fields are hex (same shape as the other
 * consent functions); `prvHex` is the 32-byte private key.
 */
public func signConsentEddsa(prvHex: String, dogTagIdHex: String, recordTypeHex: String, purposeHex: String, credentialRootHex: String, challengeHex: String, relayerHex: String, subjectHex: String, nonceHex: String, deadlineHex: String)throws  -> EddsaSignatureFfi {
    return try  FfiConverterTypeEddsaSignatureFfi.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_sign_consent_eddsa(
        FfiConverterString.lower(prvHex),
        FfiConverterString.lower(dogTagIdHex),
        FfiConverterString.lower(recordTypeHex),
        FfiConverterString.lower(purposeHex),
        FfiConverterString.lower(credentialRootHex),
        FfiConverterString.lower(challengeHex),
        FfiConverterString.lower(relayerHex),
        FfiConverterString.lower(subjectHex),
        FfiConverterString.lower(nonceHex),
        FfiConverterString.lower(deadlineHex),$0
    )
})
}
/**
 * keccak256 of the EIP-712 VerificationConsent type string (0x.. 32-byte hex).
 */
public func verificationConsentTypehashHex() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_dogtag_standard_fn_func_verification_consent_typehash_hex($0
    )
})
}
/**
 * Verify an EdDSA-BabyJubjub Poseidon consent signature against the public key (Ax,Ay) and the
 * consent fields. Mirrors circomlibjs `verifyPoseidon`. Returns true/false (no throw).
 */
public func verifyConsentEddsa(axHex: String, ayHex: String, r8xHex: String, r8yHex: String, sDec: String, dogTagIdHex: String, recordTypeHex: String, purposeHex: String, credentialRootHex: String, challengeHex: String, relayerHex: String, subjectHex: String, nonceHex: String, deadlineHex: String)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_verify_consent_eddsa(
        FfiConverterString.lower(axHex),
        FfiConverterString.lower(ayHex),
        FfiConverterString.lower(r8xHex),
        FfiConverterString.lower(r8yHex),
        FfiConverterString.lower(sDec),
        FfiConverterString.lower(dogTagIdHex),
        FfiConverterString.lower(recordTypeHex),
        FfiConverterString.lower(purposeHex),
        FfiConverterString.lower(credentialRootHex),
        FfiConverterString.lower(challengeHex),
        FfiConverterString.lower(relayerHex),
        FfiConverterString.lower(subjectHex),
        FfiConverterString.lower(nonceHex),
        FfiConverterString.lower(deadlineHex),$0
    )
})
}
/**
 * The pure §11.3 integrity pillar over a WrappedDoc JSON: rebuild the whole tree and compare to
 * targetHash/merkleRoot. This is what mobile runs OFFLINE. Returns "VALID" / "INVALID".
 */
public func verifyIntegrity(wrappedDocJson: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_verify_integrity(
        FfiConverterString.lower(wrappedDocJson),$0
    )
})
}
/**
 * The IssuerRegistry whitelist key the VerificationRegistry checks for the relayer on a given
 * purpose label: `keccak256(abi.encode("VERIFY:", purpose_key(label)))` as `0x..` hex.
 *
 * Used by the mobile pre-proof check (`IssuerRegistry.isWhitelistedFor(key, relayer)`). Available
 * even without the `prover` feature. Byte-for-byte parity with backend `verify.rs::verify_key`.
 */
public func verifyWhitelistKeyHex(purposeLabel: String) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_dogtag_standard_fn_func_verify_whitelist_key_hex(
        FfiConverterString.lower(purposeLabel),$0
    )
})
}
/**
 * wrapDocument — typed credential JSON + issuer JSON -> WrappedDoc JSON. Salts come from the OS
 * RNG (each leaf gets 16 fresh bytes). Mirrors `wrap::wrap_document`.
 */
public func wrapDocumentJson(typedCredentialJson: String, issuerJson: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_dogtag_standard_fn_func_wrap_document_json(
        FfiConverterString.lower(typedCredentialJson),
        FfiConverterString.lower(issuerJson),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_dogtag_standard_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_babyjub_consent_key_from_prv() != 49002) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_bind_consent_key_digest_hex() != 11165) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_build_merkle_root_hex() != 1024) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_bytes_to_field_hex() != 34986) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_consent_nullifier_hex() != 25451) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_derive_babyjub_consent_key() != 57121) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_dog_tag_id_field_hex() != 50191) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_eddsa_consent_message_hex() != 65311) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_hash_leaf_hex() != 23706) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_key_hash_hex() != 11418) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_nfc_normalize() != 7804) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_prove_verification() != 3014) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_sign_consent_eddsa() != 33682) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_verification_consent_typehash_hex() != 21064) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_verify_consent_eddsa() != 58972) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_verify_integrity() != 1032) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_verify_whitelist_key_hex() != 28611) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_dogtag_standard_checksum_func_wrap_document_json() != 24325) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all