//! Level-B profile-tree parity - the Rust device-side builder primitives vs the CIRCUIT's notion of
//! `R`.
//!
//! `contracts/test/consent-fixture.json` is generated by `circuits/scripts/gen-consent-fixture.mjs`
//! and carries a REAL Groth16 proof whose public `R` is verified on-chain by
//! `ConsentRegistry.t.sol` / `CustodialIssuance.t.sol`. So that `R` is not a self-asserted constant:
//! it is a root the M2 circuit proved inclusion against and the M4 registry accepted.
//!
//! Rebuilding the SAME `R` here from the SAME witness proves the Rust reserved-leaf encoding
//! (`hash_reserved_leaf`'s raw-field value slot, the pinned keyPaths, typeTag=5) and the M1 fold
//! agree with the circuit - which is exactly what `DogTagSBTConsent.profileRoot` must equal.
//!
//! This is one leg of the cross-language contract for M5 issuance. If it fails, the device would
//! build a tree the circuit cannot prove and the registry would reject every verify with
//! `R !profileRoot`.

use ark_bn254::Fr;
use ark_ff::PrimeField;
use dogtag_standard::eddsa::consent_key_from_raw_prv;
use dogtag_standard::field::{field_from_scalar_bytes, field_from_uint, to_hex32};
use dogtag_standard::leaf::{field_of_keypath, field_of_value};
use dogtag_standard::merkle::build_merkle;
use dogtag_standard::poseidon::{poseidon, DS_LEAF, DS_NULLIFIER};
use dogtag_standard::profile_tree::{
    build_profile_tree, device_root_fixture_witness, hash_reserved_leaf, KP_CONSENT_KEY,
    KP_OWNER_ADDRESS, KP_OWNER_SECRET,
};
use serde_json::Value;

const FIXTURE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../contracts/test/consent-fixture.json"
);

const DEVICE_ROOT: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../contracts/test/device-profile-root.json"
);

fn fixture() -> Value {
    let raw = std::fs::read_to_string(FIXTURE).unwrap_or_else(|e| {
        panic!("read {FIXTURE}: {e} - regenerate with `node circuits/scripts/gen-consent-fixture.mjs`")
    });
    serde_json::from_str(&raw).unwrap()
}

/// `saltField(seed)` from gen-consent-fixture.mjs:70-74 - the fixture's deterministic 16-byte salt.
fn salt16(seed: u64) -> [u8; 16] {
    let mut b = [0u8; 16];
    for (i, out) in b.iter_mut().enumerate() {
        *out = ((seed.wrapping_mul(31).wrapping_add(i as u64 * 7 + 1)) & 0xff) as u8;
    }
    b
}

fn fr_from_hex(h: &str) -> Fr {
    let s = h.strip_prefix("0x").unwrap_or(h);
    Fr::from_be_bytes_mod_order(&hex::decode(s).expect("hex"))
}

/// The fixture's attribute leaves are opaque filler (the circuit only constrains the three reserved
/// leaves), so the generator hashes them with a RAW value slot too. Mirrors `hashLeaf5` there.
fn hash_raw_leaf(key_path_field: Fr, salt: &[u8; 16], tag: u64, value: Fr) -> Fr {
    poseidon(&[
        Fr::from(DS_LEAF),
        key_path_field,
        field_from_scalar_bytes(salt),
        field_from_uint(tag),
        value,
    ])
}

/// Rebuild the fixture's exact witness and assert the Rust-built root == the on-chain-verified `R`.
#[test]
fn rust_device_built_root_equals_the_circuits_verified_root() {
    let f = fixture();

    // --- the fixture's witness (gen-consent-fixture.mjs:88-134) ---
    let owner_address = fr_from_hex(f["_ownerAddress"].as_str().unwrap());
    let owner_secret =
        fr_from_hex("0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef");

    let prv: [u8; 32] = hex::decode("0001020304050607080900010203040506070809000102030405060708090001")
        .unwrap()
        .try_into()
        .unwrap();
    let key = consent_key_from_raw_prv(&prv);
    let key_hash = poseidon(&[key.ax, key.ay]);

    // --- the three reserved leaves, via the PRODUCTION builder primitive ---
    let owner_leaf = hash_reserved_leaf(KP_OWNER_ADDRESS, &salt16(11), owner_address).unwrap();
    let key_leaf = hash_reserved_leaf(KP_CONSENT_KEY, &salt16(22), key_hash).unwrap();
    let secret_leaf = hash_reserved_leaf(KP_OWNER_SECRET, &salt16(33), owner_secret).unwrap();

    // --- the fixture's five opaque attribute leaves ---
    let mut leaves = vec![owner_leaf, key_leaf, secret_leaf];
    for i in 0u64..5 {
        leaves.push(hash_raw_leaf(
            field_of_keypath(&format!("credentialSubject.attr{i}")),
            &salt16(100 + i),
            (i % 4) + 1,
            Fr::from(700000 + i * 101),
        ));
    }

    let root = build_merkle(&leaves).root;
    assert_eq!(
        to_hex32(&root),
        f["R"].as_str().unwrap(),
        "Rust-built R != the R the circuit proved and the registry verified on-chain"
    );
}

/// Drift guard for the Rust→Solidity bridge: `contracts/test/device-profile-root.json` must still
/// be what the device builder produces. `CustodialIssuance.t.sol` mints that file's `R` and asserts
/// `profileRoot(dogTagId) == R`; if the builder moves `R` and the file is not regenerated, the two
/// sides would silently stop describing the same tree. This fails first, with the fix in the message.
#[test]
fn committed_device_profile_root_matches_a_fresh_device_build() {
    let raw = std::fs::read_to_string(DEVICE_ROOT).unwrap_or_else(|e| {
        panic!("read {DEVICE_ROOT}: {e} - run `cargo run -p dogtag-standard-rs --bin gen-device-profile-root`")
    });
    let committed: Value = serde_json::from_str(&raw).unwrap();

    let w = device_root_fixture_witness();
    let built = build_profile_tree(&w.seed, w.dog_tag_id, &w.owner_address, &w.attributes).unwrap();

    assert_eq!(
        committed["R"].as_str().unwrap(),
        to_hex32(&built.root),
        "device-profile-root.json is stale - regenerate: \
         cargo run -p dogtag-standard-rs --bin gen-device-profile-root"
    );
    assert_eq!(committed["dogTagId"].as_str().unwrap(), w.dog_tag_id_dec);
}

/// The owner-secret is the NULLIFIER's secret leaf - assert the same secret that sits in the tree
/// reproduces the fixture's on-chain nullifier under the Level-B preimage
/// `Poseidon6(DS_NULLIFIER, ownerSecret, dogTagId, purpose, relayer, consentNonce)`.
/// This is what makes the nullifier owner-private: only the device knows `ownerSecret`.
#[test]
fn the_owner_secret_reproduces_the_fixtures_nullifier() {
    let f = fixture();
    let owner_secret =
        fr_from_hex("0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef");

    // dogTagId is the CANONICAL field `field_of_value(Integer(handle))` — the fixture (regenerated
    // by M7 P0) binds the canonical field, not the raw `424242n` handle (ZK cross-check §2).
    let dog_tag_id = field_of_value(&dogtag_standard::types::TypedScalar::Integer("424242".to_string()))
        .expect("canonical dogTagId field");
    let nullifier = poseidon(&[
        Fr::from(DS_NULLIFIER),
        owner_secret,
        dog_tag_id,                                           // dogTagId (canonical field)
        fr_from_hex(f["purpose"].as_str().unwrap()),          // purpose
        fr_from_hex(f["relayer"].as_str().unwrap()),          // relayer (uint160)
        Fr::from(99u64),                                      // consentNonce
    ]);

    assert_eq!(
        to_hex32(&nullifier),
        f["nullifier"].as_str().unwrap(),
        "owner-secret does not reproduce the circuit's nullifier"
    );
}
