import { describe, expect, it } from "vitest";
import {
  EARTH_RADIUS_KM,
  MAX_DISTANCE_KM,
  haversineKm,
  isValidLatLng,
  sortByDistance,
  withinRadiusKm,
  type LatLng,
} from "../src/geo/distance";
import { compassPoint8, compassPoint16, initialBearingDeg } from "../src/geo/bearing";
import { formatDistanceKm, unitSystemForRegion, KM_PER_MILE } from "../src/geo/format";
import {
  decodeGeohash,
  encodeGeohash,
  geohashCellContains,
  GEOHASH_BASE32,
  MAX_GEOHASH_PRECISION,
} from "../src/geo/geohash";

/**
 * The on-device geo core.
 *
 * The properties that actually matter, and the reason each is here rather than being a rounding
 * quibble:
 *
 *   * NO INPUT MAY YIELD NaN. A NaN distance collapses to `false` in a radius filter, so a "could
 *     not compute" would render as a definite "out of range" - exactly the class of over-claim this
 *     codebase removes everywhere else. That is the whole reason the implementation uses `atan2`
 *     rather than the `asin` form the deprecated server filter uses.
 *   * AN UNDEFINED ANSWER IS `null`, NEVER A PLAUSIBLE NUMBER. Bearing between identical points is
 *     the sharp one: `atan2(0, 0)` is `0`, which a caller prints as "N".
 *   * THE ANTIMERIDIAN AND THE POLES ARE ORDINARY. Both are where naive implementations produce
 *     answers that are wrong by half a planet while looking perfectly well-formed.
 *
 * Cross-language parity with the deprecated server filter lives in `geoParity.test.ts`, against a
 * fixture generated by the Rust itself.
 */

const P = (lat: number, lng: number): LatLng => ({ lat, lng });

/**
 * The naive equirectangular approximation, present ONLY as a foil.
 *
 * It treats a degree of longitude as a constant width, which is true at the equator and increasingly
 * false toward the poles. Several tests below assert the real implementation does NOT agree with it,
 * because "distance" implementations that quietly do this are common and the failure is invisible at
 * the equator where people test.
 */
const equirectangularKm = (a: LatLng, b: LatLng): number => {
  const dLat = ((b.lat - a.lat) * Math.PI) / 180;
  const dLng = ((b.lng - a.lng) * Math.PI) / 180;
  return Math.hypot(dLat, dLng) * EARTH_RADIUS_KM;
};

// =============================================================================================
// distance
// =============================================================================================

describe("haversineKm - identical points", () => {
  it("is exactly zero, at the equator and at high latitude", () => {
    expect(haversineKm(P(0, 0), P(0, 0))).toBe(0);
    expect(haversineKm(P(51.5074, -0.1278), P(51.5074, -0.1278))).toBe(0);
    expect(haversineKm(P(-89.9, 173.2), P(-89.9, 173.2))).toBe(0);
  });

  it("is symmetric", () => {
    const a = P(1.3521, 103.8198);
    const b = P(51.5074, -0.1278);
    expect(haversineKm(a, b)).toBeCloseTo(haversineKm(b, a), 9);
  });
});

describe("haversineKm - the equator-versus-high-latitude difference", () => {
  it("shrinks a degree of longitude by cos(latitude)", () => {
    // The property a naive implementation loses. One degree of longitude is ~111 km at the equator,
    // ~55.6 km at 60°N (cos 60° = 0.5), ~19.3 km at 80°N.
    const atEquator = haversineKm(P(0, 0), P(0, 1));
    const at60 = haversineKm(P(60, 0), P(60, 1));
    const at80 = haversineKm(P(80, 0), P(80, 1));

    expect(atEquator).toBeCloseTo(111.195, 2);
    expect(at60).toBeCloseTo(atEquator * Math.cos((60 * Math.PI) / 180), 1);
    expect(at80).toBeCloseTo(atEquator * Math.cos((80 * Math.PI) / 180), 1);
    expect(at60).toBeLessThan(atEquator);
    expect(at80).toBeLessThan(at60);
  });

  it("agrees with the naive approximation at the equator and diverges from it at high latitude", () => {
    // At the equator the naive form is right, which is why this bug survives casual testing.
    expect(haversineKm(P(0, 0), P(0, 1))).toBeCloseTo(equirectangularKm(P(0, 0), P(0, 1)), 3);

    // At 60°N the naive form is wrong by ~55 km on a 55 km leg - a 100% error.
    const real = haversineKm(P(60, 0), P(60, 1));
    const naive = equirectangularKm(P(60, 0), P(60, 1));
    expect(naive - real).toBeGreaterThan(50);

    // At 80°N it is wrong by nearly 6x.
    expect(equirectangularKm(P(80, 0), P(80, 1)) / haversineKm(P(80, 0), P(80, 1))).toBeGreaterThan(5);
  });

  it("a degree of LATITUDE is the same length everywhere", () => {
    // The counterpart: only longitude shrinks. A implementation that scaled both would fail here.
    const atEquator = haversineKm(P(0, 0), P(1, 0));
    const at60 = haversineKm(P(60, 0), P(61, 0));
    const at80 = haversineKm(P(80, 0), P(81, 0));
    expect(at60).toBeCloseTo(atEquator, 6);
    expect(at80).toBeCloseTo(atEquator, 6);
  });
});

describe("haversineKm - the antimeridian", () => {
  it("treats 179.9 to -179.9 as 0.2 degrees apart, not 359.8", () => {
    // The classic failure: subtracting raw longitudes gives 359.8°, so a 22 km hop is reported as
    // ~40000 km. The formula is periodic in Δλ, so no pre-normalisation is needed.
    const across = haversineKm(P(0, 179.9), P(0, -179.9));
    const equivalent = haversineKm(P(0, -0.1), P(0, 0.1));
    expect(across).toBeCloseTo(equivalent, 9);
    expect(across).toBeCloseTo(22.239, 2);
  });

  it("crosses at high latitude too, where the leg is shorter", () => {
    const at60 = haversineKm(P(60, 179.9), P(60, -179.9));
    expect(at60).toBeCloseTo(haversineKm(P(60, -0.1), P(60, 0.1)), 9);
    expect(at60).toBeLessThan(haversineKm(P(0, 179.9), P(0, -179.9)));
  });

  it("is unaffected by which side of the antimeridian a longitude is expressed on", () => {
    // 180 and -180 are the same meridian.
    expect(haversineKm(P(10, 180), P(10, 179))).toBeCloseTo(haversineKm(P(10, -180), P(10, 179)), 9);
  });
});

describe("haversineKm - the poles", () => {
  it("pole to equator is a quarter circumference", () => {
    const quarter = MAX_DISTANCE_KM / 2;
    expect(haversineKm(P(90, 0), P(0, 0))).toBeCloseTo(quarter, 6);
    expect(haversineKm(P(-90, 0), P(0, 0))).toBeCloseTo(quarter, 6);
    // Longitude of the equatorial end does not matter - every meridian meets the pole.
    expect(haversineKm(P(90, 0), P(0, 137))).toBeCloseTo(quarter, 6);
  });

  it("pole to pole is the half circumference", () => {
    expect(haversineKm(P(90, 0), P(-90, 0))).toBeCloseTo(MAX_DISTANCE_KM, 6);
    expect(haversineKm(P(90, 45), P(-90, -170))).toBeCloseTo(MAX_DISTANCE_KM, 6);
  });

  it("is ~zero between two points at the same pole regardless of longitude", () => {
    // Longitude is meaningless at a pole: these are the same physical point. `cos(90°)` is 6.1e-17
    // rather than exactly 0 in f64, so this is vanishingly small rather than exactly 0.
    expect(haversineKm(P(90, 0), P(90, 73))).toBeLessThan(1e-9);
    expect(haversineKm(P(-90, -12), P(-90, 154))).toBeLessThan(1e-9);
  });
});

describe("haversineKm - totality (the reason for `atan2` over `asin`)", () => {
  it("never returns NaN for exact antipodes", () => {
    for (const [lat, lng] of [
      [0, 0], [45, -93], [-33.86, 151.21], [89.9, 0], [-89.9, 12], [1.3521, 103.8198],
    ] as const) {
      const anti = P(-lat, lng > 0 ? lng - 180 : lng + 180);
      const d = haversineKm(P(lat, lng), anti);
      expect(Number.isNaN(d), `NaN at antipode of ${lat},${lng}`).toBe(false);
      expect(d).toBeCloseTo(MAX_DISTANCE_KM, 3);
    }
  });

  it("never returns NaN across a dense sweep of near-antipodal pairs", () => {
    // The exact pairs that break `asin(sqrt(a))` differ between engines because `sin`/`cos` disagree
    // in the last ulp, so this sweeps rather than pinning one pair. Roughly 1 in 12,000 of these
    // would be NaN under the deprecated form.
    let worst = 0;
    for (let i = 0; i < 20000; i += 1) {
      const lat = -90 + (180 * i) / 20000;
      const lng = -180 + (360 * ((i * 7919) % 20000)) / 20000;
      const jitter = ((i % 97) - 48) * 1e-11;
      const d = haversineKm(P(lat, lng), P(-lat + jitter, lng > 0 ? lng - 180 : lng + 180));
      expect(Number.isNaN(d), `NaN at ${lat},${lng}`).toBe(false);
      worst = Math.max(worst, Math.abs(d - MAX_DISTANCE_KM));
    }
    // All of them really are near-antipodal, so none should be far off the half-circumference.
    expect(worst).toBeLessThan(1);
  });

  it("never exceeds the half circumference", () => {
    for (let i = 0; i < 5000; i += 1) {
      const a = P(-90 + (180 * i) / 5000, -180 + (360 * ((i * 31) % 5000)) / 5000);
      const b = P(90 - (180 * i) / 5000, 180 - (360 * ((i * 17) % 5000)) / 5000);
      const d = haversineKm(a, b);
      expect(d).toBeGreaterThanOrEqual(0);
      // A tiny tolerance for the last-ulp rounding at exact antipodes.
      expect(d).toBeLessThanOrEqual(MAX_DISTANCE_KM + 1e-6);
    }
  });

  it("handles sub-metre separations without collapsing to zero", () => {
    const d = haversineKm(P(0, 0), P(0, 0.000001));
    expect(d).toBeGreaterThan(0);
    expect(d).toBeCloseTo(0.00011119, 8);
  });
});

describe("isValidLatLng", () => {
  it("accepts the full legal range including the boundaries", () => {
    for (const p of [P(0, 0), P(90, 180), P(-90, -180), P(51.5, -0.12)]) {
      expect(isValidLatLng(p)).toBe(true);
    }
  });

  it("rejects out-of-range, non-finite, and absent positions", () => {
    for (const p of [
      P(91, 0), P(-91, 0), P(0, 181), P(0, -181),
      P(NaN, 0), P(0, NaN), P(Infinity, 0), P(0, -Infinity),
    ]) {
      expect(isValidLatLng(p)).toBe(false);
    }
    expect(isValidLatLng(null)).toBe(false);
    expect(isValidLatLng(undefined)).toBe(false);
  });
});

describe("withinRadiusKm", () => {
  it("is inclusive at the boundary, matching the deprecated `<=` filter", () => {
    const a = P(0, 0);
    const b = P(0, 1);
    const exact = haversineKm(a, b);
    expect(withinRadiusKm(a, b, exact)).toBe(true);
    expect(withinRadiusKm(a, b, exact * (1 - 1e-12))).toBe(false);
  });

  it("admits a point at zero distance from itself even at radius 0", () => {
    expect(withinRadiusKm(P(12, 34), P(12, 34), 0)).toBe(true);
  });

  it("does NOT admit an unusable coordinate on either side", () => {
    // The core rule: a position we cannot evaluate is not "nearby". Admitting it would be the same
    // as treating a missing distance as 0.
    expect(withinRadiusKm(P(NaN, 0), P(0, 0), 1e9)).toBe(false);
    expect(withinRadiusKm(P(0, 0), P(0, NaN), 1e9)).toBe(false);
    expect(withinRadiusKm(P(999, 999), P(0, 0), 1e9)).toBe(false);
  });

  it("does not admit anything for a nonsensical radius", () => {
    expect(withinRadiusKm(P(0, 0), P(0, 0), -1)).toBe(false);
    expect(withinRadiusKm(P(0, 0), P(0, 0), NaN)).toBe(false);
  });
});

// =============================================================================================
// sortByDistance
// =============================================================================================

interface Provider {
  name: string;
  pos: LatLng | null;
}
const posOf = (p: Provider) => p.pos;

describe("sortByDistance", () => {
  const here = P(1.3521, 103.8198); // Singapore
  const near: Provider = { name: "near", pos: P(1.36, 103.83) };
  const mid: Provider = { name: "mid", pos: P(1.5, 104.0) };
  const far: Provider = { name: "far", pos: P(51.5074, -0.1278) };

  it("orders nearest first", () => {
    const out = sortByDistance(here, [far, near, mid], posOf);
    expect(out.map((r) => r.item.name)).toEqual(["near", "mid", "far"]);
    expect(out[0]?.distanceKm).toBeCloseTo(1.434, 2);
  });

  it("puts items with no usable position LAST, with distanceKm null - never 0", () => {
    // The defect this prevents: a null distance compared as 0 ranks every unlocatable provider above
    // every real one, and renders as "0 m away".
    const nowhere: Provider = { name: "nowhere", pos: null };
    const bogus: Provider = { name: "bogus", pos: P(999, 999) };
    const out = sortByDistance(here, [nowhere, far, bogus, near], posOf);
    expect(out.map((r) => r.item.name)).toEqual(["near", "far", "nowhere", "bogus"]);
    expect(out[2]?.distanceKm).toBeNull();
    expect(out[3]?.distanceKm).toBeNull();
    expect(out[0]?.distanceKm).not.toBe(0);
  });

  it("keeps unlocatable items in their input order", () => {
    const a: Provider = { name: "a", pos: null };
    const b: Provider = { name: "b", pos: undefined as unknown as null };
    const c: Provider = { name: "c", pos: P(NaN, NaN) };
    const out = sortByDistance(here, [a, b, c], posOf);
    expect(out.map((r) => r.item.name)).toEqual(["a", "b", "c"]);
  });

  it("is stable for equidistant items", () => {
    const first: Provider = { name: "first", pos: P(2, 103.8198) };
    const second: Provider = { name: "second", pos: P(2, 103.8198) };
    const out = sortByDistance(here, [first, second], posOf);
    expect(out.map((r) => r.item.name)).toEqual(["first", "second"]);
  });

  it("ranks nothing when the ORIGIN is unusable, but still returns every item in input order", () => {
    // The caller still has a list to render; it just has no distances to put on it. That is not an
    // error, and silently dropping the items would be worse than showing them undistanced.
    const out = sortByDistance(P(NaN, NaN), [far, near, mid], posOf);
    expect(out.map((r) => r.item.name)).toEqual(["far", "near", "mid"]);
    expect(out.every((r) => r.distanceKm === null)).toBe(true);
  });

  it("does not mutate the input array", () => {
    const input = [far, near, mid];
    const snapshot = [...input];
    sortByDistance(here, input, posOf);
    expect(input).toEqual(snapshot);
  });

  it("handles an empty list", () => {
    expect(sortByDistance(here, [], posOf)).toEqual([]);
  });

  it("sorts correctly across the antimeridian", () => {
    // A provider 0.1° east of the antimeridian is nearer to one 0.1° west than a provider 5° away on
    // the same side. A raw-longitude sort would invert this.
    const origin = P(0, 179.95);
    const acrossTheLine: Provider = { name: "across", pos: P(0, -179.95) };
    const sameSide: Provider = { name: "sameSide", pos: P(0, 174) };
    const out = sortByDistance(origin, [sameSide, acrossTheLine], posOf);
    expect(out.map((r) => r.item.name)).toEqual(["across", "sameSide"]);
  });
});

// =============================================================================================
// bearing
// =============================================================================================

describe("initialBearingDeg - the cardinal directions", () => {
  it("reads N / E / S / W from the equator", () => {
    expect(initialBearingDeg(P(0, 0), P(1, 0))).toBeCloseTo(0, 6);
    expect(initialBearingDeg(P(0, 0), P(0, 1))).toBeCloseTo(90, 6);
    expect(initialBearingDeg(P(0, 0), P(-1, 0))).toBeCloseTo(180, 6);
    expect(initialBearingDeg(P(0, 0), P(0, -1))).toBeCloseTo(270, 6);
  });

  it("is always in [0, 360)", () => {
    for (let i = 0; i < 720; i += 1) {
      const b = initialBearingDeg(P(0, 0), P(Math.sin(i) * 45, Math.cos(i) * 90));
      if (b === null) continue;
      expect(b).toBeGreaterThanOrEqual(0);
      expect(b).toBeLessThan(360);
    }
  });

  it("returns 0 rather than 360 for due north", () => {
    // `(-0 + 360) % 360` is 0; without the second modulo this would be 360 and fall outside range.
    expect(initialBearingDeg(P(-10, 5), P(10, 5))).toBe(0);
  });

  it("reads correctly across the antimeridian", () => {
    // Going from 179.9 to -179.9 is EAST (bearing ~90), not west.
    const b = initialBearingDeg(P(0, 179.9), P(0, -179.9));
    expect(b).toBeCloseTo(90, 3);
  });

  it("points due north toward the north pole from anywhere", () => {
    // The DESTINATION being a pole is not degenerate.
    expect(initialBearingDeg(P(45, 12), P(90, 0))).toBeCloseTo(0, 6);
    expect(initialBearingDeg(P(-30, -170), P(90, 88))).toBeCloseTo(0, 6);
    expect(initialBearingDeg(P(45, 12), P(-90, 0))).toBeCloseTo(180, 6);
  });
});

describe("initialBearingDeg - the undefined cases return null, never a direction", () => {
  it("identical points", () => {
    // `atan2(0, 0)` is 0, which renders as "N" - a heading manufactured from nothing.
    expect(initialBearingDeg(P(0, 0), P(0, 0))).toBeNull();
    expect(initialBearingDeg(P(51.5074, -0.1278), P(51.5074, -0.1278))).toBeNull();
  });

  it("an origin at a pole, where north is not a direction", () => {
    expect(initialBearingDeg(P(90, 0), P(0, 0))).toBeNull();
    expect(initialBearingDeg(P(-90, 0), P(0, 0))).toBeNull();
    // The specific wrong answer this prevents: at the north pole the formula reports "east" for a
    // target 90° of longitude away, when in truth every direction from there is south.
    expect(initialBearingDeg(P(90, 0), P(0, 90))).toBeNull();
  });

  it("unusable coordinates on either side", () => {
    expect(initialBearingDeg(P(NaN, 0), P(0, 0))).toBeNull();
    expect(initialBearingDeg(P(0, 0), P(0, NaN))).toBeNull();
    expect(initialBearingDeg(P(0, 0), P(91, 0))).toBeNull();
  });

});

describe("initialBearingDeg - antipodes are ambiguous but NOT undefined", () => {
  it("returns a heading that really does reach the destination", () => {
    // Deliberately not `null`. Between antipodes every great circle is a shortest path, so the
    // bearing is not unique - but due east along the equator genuinely reaches (0, 180), so 90 is
    // one of several right answers rather than a manufactured one. That is a different situation
    // from identical points, where no path exists at all and `atan2(0, 0)` would print "N".
    const b = initialBearingDeg(P(0, 0), P(0, 180));
    expect(b).not.toBeNull();
    expect(b).toBeCloseTo(90, 6);
  });

  it("still refuses when the ambiguity is compounded by a degenerate origin", () => {
    // Pole-to-pole is antipodal AND origin-at-a-pole. The pole rule wins.
    expect(initialBearingDeg(P(90, 0), P(-90, 0))).toBeNull();
  });
});

describe("compass rendering", () => {
  it("maps the eight points", () => {
    const expected: Array<[number, string]> = [
      [0, "N"], [45, "NE"], [90, "E"], [135, "SE"],
      [180, "S"], [225, "SW"], [270, "W"], [315, "NW"],
    ];
    for (const [deg, label] of expected) expect(compassPoint8(deg)).toBe(label);
  });

  it("wraps 360 back to N rather than off the end of the rose", () => {
    // The index is `round(deg / 45)`, which is 8 at 360 - one past the end of an 8-element array.
    // Without the trailing `% 8` this would be `undefined`.
    expect(compassPoint8(360)).toBe("N");
    expect(compassPoint8(359)).toBe("N");
    expect(compassPoint8(330)).toBe("NW");
    expect(compassPoint16(360)).toBe("N");
    expect(compassPoint16(349)).toBe("N");
  });

  it("rounds half away from the origin at a sector boundary, consistently", () => {
    // 337.5 is exactly the NW/N boundary. `Math.round` is half-up, so it lands on N. Pinned because
    // it is the kind of edge a refactor silently flips, not because either answer is wrong.
    expect(compassPoint8(337.5)).toBe("N");
    expect(compassPoint8(337.4)).toBe("NW");
    expect(compassPoint8(22.5)).toBe("NE");
    expect(compassPoint8(22.4)).toBe("N");
  });

  it("accepts out-of-range degrees by normalising rather than returning nothing", () => {
    expect(compassPoint8(450)).toBe("E");
    expect(compassPoint8(-90)).toBe("W");
    expect(compassPoint16(-22.5)).toBe("NNW");
  });

  it("maps the sixteen points at their boundaries", () => {
    expect(compassPoint16(0)).toBe("N");
    expect(compassPoint16(22.5)).toBe("NNE");
    expect(compassPoint16(45)).toBe("NE");
    expect(compassPoint16(202.5)).toBe("SSW");
    expect(compassPoint16(292.5)).toBe("WNW");
  });

  it("propagates null so a caller can never print a direction that was not established", () => {
    expect(compassPoint8(null)).toBeNull();
    expect(compassPoint16(null)).toBeNull();
    expect(compassPoint8(NaN)).toBeNull();
    expect(compassPoint16(Infinity)).toBeNull();
  });

  it("composes with a null bearing end-to-end", () => {
    expect(compassPoint8(initialBearingDeg(P(5, 5), P(5, 5)))).toBeNull();
  });
});

// =============================================================================================
// format
// =============================================================================================

describe("formatDistanceKm - metric", () => {
  it("uses the sub-10 m floor rather than inventing metre resolution", () => {
    // A GPS fix is good to 5-20 m. "3 m" would be fiction dressed as measurement.
    expect(formatDistanceKm(0)).toBe("< 10 m");
    expect(formatDistanceKm(0.003)).toBe("< 10 m");
    expect(formatDistanceKm(0.0099)).toBe("< 10 m");
  });

  it("rounds to 10 m below a kilometre", () => {
    expect(formatDistanceKm(0.01)).toBe("10 m");
    expect(formatDistanceKm(0.823)).toBe("820 m");
    expect(formatDistanceKm(0.826)).toBe("830 m");
    expect(formatDistanceKm(0.994)).toBe("990 m");
  });

  it("promotes to kilometres when rounding pushes a value out of the metre band", () => {
    // 999 m rounds to 1000, which is a kilometre and should read as one rather than as "1000 m".
    // Same rule as the 9.97 -> "10 km" case: the band is decided after rounding, not before.
    expect(formatDistanceKm(0.999)).toBe("1.0 km");
    expect(formatDistanceKm(0.9999)).toBe("1.0 km");
    expect(formatDistanceKm(0.995)).toBe("1.0 km");
  });

  it("never shows more precision than it has", () => {
    // The claim under test: no output carries a digit finer than 10 m / 0.1 km / 1 km for its band.
    expect(formatDistanceKm(0.8231)).toBe("820 m");
    expect(formatDistanceKm(3.4499)).toBe("3.4 km");
    expect(formatDistanceKm(27.49)).toBe("27 km");
  });

  it("shows one decimal from 1 to 10 km", () => {
    expect(formatDistanceKm(1)).toBe("1.0 km");
    expect(formatDistanceKm(3.44)).toBe("3.4 km");
    expect(formatDistanceKm(9.94)).toBe("9.9 km");
  });

  it("shows whole kilometres at and above 10", () => {
    expect(formatDistanceKm(10)).toBe("10 km");
    expect(formatDistanceKm(27.4)).toBe("27 km");
    expect(formatDistanceKm(10847.8)).toBe("10848 km");
  });

  it("does not print a trailing zero it did not measure at the band edge", () => {
    // 9.97 rounds to 10.0, which must render as "10 km" rather than "10.0 km".
    expect(formatDistanceKm(9.97)).toBe("10 km");
  });
});

describe("formatDistanceKm - imperial", () => {
  it("uses the sub-25 ft floor", () => {
    expect(formatDistanceKm(0, "imperial")).toBe("< 25 ft");
    expect(formatDistanceKm(0.005, "imperial")).toBe("< 25 ft");
  });

  it("rounds to 25 ft below a tenth of a mile", () => {
    expect(formatDistanceKm(0.1, "imperial")).toBe("325 ft");
    expect(formatDistanceKm(0.15, "imperial")).toBe("500 ft");
  });

  it("shows one decimal up to 10 miles, then whole miles", () => {
    expect(formatDistanceKm(KM_PER_MILE, "imperial")).toBe("1.0 mi");
    expect(formatDistanceKm(KM_PER_MILE * 3.44, "imperial")).toBe("3.4 mi");
    expect(formatDistanceKm(KM_PER_MILE * 17, "imperial")).toBe("17 mi");
  });

  it("does not print a trailing zero at the band edge", () => {
    expect(formatDistanceKm(KM_PER_MILE * 9.97, "imperial")).toBe("10 mi");
  });

  it("crosses from feet to miles at the right point", () => {
    expect(formatDistanceKm(KM_PER_MILE * 0.0999, "imperial")).toMatch(/ft$/);
    expect(formatDistanceKm(KM_PER_MILE * 0.1001, "imperial")).toMatch(/mi$/);
  });
});

describe("formatDistanceKm - nothing to render", () => {
  it("returns null for absent, non-finite, or negative input", () => {
    // So a caller can render `formatDistanceKm(r.distanceKm)` directly and never print a distance
    // that was not computed.
    for (const bad of [null, undefined, NaN, Infinity, -Infinity, -1]) {
      expect(formatDistanceKm(bad)).toBeNull();
      expect(formatDistanceKm(bad, "imperial")).toBeNull();
    }
  });

  it("composes with sortByDistance's null distance", () => {
    const out = sortByDistance(P(0, 0), [{ name: "x", pos: null }], (p) => p.pos);
    expect(formatDistanceKm(out[0]?.distanceKm)).toBeNull();
  });
});

describe("unitSystemForRegion", () => {
  it("picks imperial for the regions that sign roads in miles", () => {
    for (const r of ["US", "us", "GB", "LR", "MM", "en-US", "en-GB", "en-Latn-US", "my_MM"]) {
      expect(unitSystemForRegion(r), r).toBe("imperial");
    }
  });

  it("defaults to metric for everything else, including absent input", () => {
    for (const r of ["SG", "fr-FR", "de", "ja-JP", "", null, undefined, "zz"]) {
      expect(unitSystemForRegion(r)).toBe("metric");
    }
  });

  it("does not mistake a language subtag for a region", () => {
    // "in" is the legacy code for Indonesian, not India; "us" alone is a region and IS imperial.
    expect(unitSystemForRegion("in-ID")).toBe("metric");
    expect(unitSystemForRegion("us")).toBe("imperial");
  });
});

// =============================================================================================
// geohash
// =============================================================================================

describe("encodeGeohash", () => {
  it("matches the published reference vectors", () => {
    // The canonical example from the original geohash.org write-up.
    expect(encodeGeohash(57.64911, 10.40744, 11)).toBe("u4pruydqqvj");
    // The widely-cited Curitiba vector.
    expect(encodeGeohash(-25.382708, -49.265506, 12)).toBe("6gkzwgjzn820");
  });

  it("agrees with an independent decode of its own output", () => {
    // Not a published vector - a self-check, and it is here because a published literal is only as
    // good as the coordinates it was published WITH. A commonly-quoted Eiffel Tower hash
    // ("u09tunquc") decodes to 48.858411, 2.294490, which is a few tens of metres from the
    // 48.858093, 2.294694 usually printed beside it; asserting that pair would have failed a correct
    // encoder. So this pins the round trip instead, which is checkable from first principles.
    const hash = encodeGeohash(48.858093, 2.294694, 9);
    expect(hash).toBe("u09tunqgn");
    const cell = decodeGeohash(hash);
    expect(cell).not.toBeNull();
    if (!cell) return;
    expect(geohashCellContains(cell, P(48.858093, 2.294694))).toBe(true);
  });

  it("is a strict prefix chain - shortening a hash always coarsens the same cell", () => {
    const full = encodeGeohash(1.3521, 103.8198, 10);
    expect(full).not.toBeNull();
    for (let p = 1; p <= 10; p += 1) {
      expect(encodeGeohash(1.3521, 103.8198, p)).toBe(full?.slice(0, p));
    }
  });

  it("uses only the geohash alphabet", () => {
    for (let i = 0; i < 200; i += 1) {
      const h = encodeGeohash(-90 + (180 * i) / 200, -180 + (360 * i) / 200, 9);
      expect(h).not.toBeNull();
      for (const ch of h ?? "") expect(GEOHASH_BASE32).toContain(ch);
    }
  });

  it("handles the extremes of the coordinate space", () => {
    for (const [lat, lng] of [
      [0, 0], [90, 180], [-90, -180], [90, -180], [-90, 180], [0, 180], [0, -180],
    ] as const) {
      const h = encodeGeohash(lat, lng, 9);
      expect(h, `${lat},${lng}`).not.toBeNull();
      expect(h).toHaveLength(9);
    }
  });

  it("returns null rather than a hash of something that was never a place", () => {
    expect(encodeGeohash(NaN, 0, 5)).toBeNull();
    expect(encodeGeohash(0, Infinity, 5)).toBeNull();
    expect(encodeGeohash(91, 0, 5)).toBeNull();
    expect(encodeGeohash(0, 181, 5)).toBeNull();
  });

  it("rejects an out-of-range or non-integer precision", () => {
    expect(encodeGeohash(0, 0, 0)).toBeNull();
    expect(encodeGeohash(0, 0, -1)).toBeNull();
    expect(encodeGeohash(0, 0, 2.5)).toBeNull();
    expect(encodeGeohash(0, 0, MAX_GEOHASH_PRECISION + 1)).toBeNull();
    expect(encodeGeohash(0, 0, MAX_GEOHASH_PRECISION)).toHaveLength(MAX_GEOHASH_PRECISION);
  });
});

describe("decodeGeohash", () => {
  it("returns a CELL, and the original point lies inside it", () => {
    // The property that makes the return type honest: decode does not recover the point, it recovers
    // the box the point was in.
    const point = P(1.3521, 103.8198);
    for (const precision of [1, 3, 5, 7, 9]) {
      const hash = encodeGeohash(point.lat, point.lng, precision);
      const cell = decodeGeohash(hash);
      expect(cell, `precision ${precision}`).not.toBeNull();
      if (!cell) continue;
      expect(geohashCellContains(cell, point)).toBe(true);
      expect(cell.precision).toBe(precision);
    }
  });

  it("reports the cell's real size, so the error is visible at the call site", () => {
    // The scouting report's figures: geohash-4 is ~39 x 19.5 km, geohash-5 ~4.9 km square.
    const c4 = decodeGeohash(encodeGeohash(0, 0, 4));
    expect(c4?.widthKm).toBeCloseTo(39.1, 0);
    expect(c4?.heightKm).toBeCloseTo(19.6, 0);

    const c5 = decodeGeohash(encodeGeohash(0, 0, 5));
    expect(c5?.widthKm).toBeCloseTo(4.9, 0);
    expect(c5?.heightKm).toBeCloseTo(4.9, 0);
  });

  it("reports a NARROWER cell at high latitude, because longitude converges", () => {
    // Why width is computed rather than read from a table: the same precision is a much narrower box
    // near the poles. A caller reasoning about disclosure needs the real number.
    const equator = decodeGeohash(encodeGeohash(0, 0, 4));
    const north = decodeGeohash(encodeGeohash(75, 0, 4));
    expect(north?.widthKm).toBeLessThan((equator?.widthKm ?? 0) / 3);
    // Height does not change - only longitude converges.
    expect(north?.heightKm).toBeCloseTo(equator?.heightKm ?? 0, 1);
  });

  it("centre is the middle of the box, and is up to half a cell from the true point", () => {
    const point = P(1.3521, 103.8198);
    const cell = decodeGeohash(encodeGeohash(point.lat, point.lng, 4));
    expect(cell).not.toBeNull();
    if (!cell) return;
    expect(cell.center.lat).toBeCloseTo((cell.lat.min + cell.lat.max) / 2, 12);
    expect(cell.center.lng).toBeCloseTo((cell.lng.min + cell.lng.max) / 2, 12);
    // The error a `decode -> {lat,lng}` signature would have hidden: kilometres, not metres.
    const err = haversineKm(point, cell.center);
    expect(err).toBeGreaterThan(1);
    expect(err).toBeLessThanOrEqual(Math.hypot(cell.widthKm, cell.heightKm) / 2 + 1e-6);
  });

  it("round-trips: re-encoding a cell's centre reproduces its hash", () => {
    for (const hash of ["u4pruydqqvj", "6gkz", "ezs42", "s", "gbsuv"]) {
      const cell = decodeGeohash(hash);
      expect(cell, hash).not.toBeNull();
      if (!cell) continue;
      expect(encodeGeohash(cell.center.lat, cell.center.lng, hash.length)).toBe(hash);
    }
  });

  it("is case-insensitive", () => {
    expect(decodeGeohash("U4PRUYDQQVJ")?.hash).toBe("u4pruydqqvj");
    expect(decodeGeohash("U4PRUYDQQVJ")?.center).toEqual(decodeGeohash("u4pruydqqvj")?.center);
  });

  it("returns null for an undecodable hash rather than a plausible wrong box", () => {
    expect(decodeGeohash("")).toBeNull();
    expect(decodeGeohash(null)).toBeNull();
    expect(decodeGeohash(undefined)).toBeNull();
    // `a`, `i`, `l`, `o` are excluded from the alphabet.
    expect(decodeGeohash("abc")).toBeNull();
    expect(decodeGeohash("u4pri")).toBeNull();
    expect(decodeGeohash("u4pr!")).toBeNull();
    expect(decodeGeohash(" u4pr")).toBeNull();
    expect(decodeGeohash("u".repeat(MAX_GEOHASH_PRECISION + 1))).toBeNull();
  });

  it("contains a point at the very top of the coordinate domain", () => {
    // The bug this pins: a strictly half-open rule leaves lat 90 and lng 180 in NO cell, because
    // there is no neighbour above them to own the edge. So `contains(decode(encode(p)), p)` was
    // false for the north pole and for every point on the +180 antimeridian - a point not inside
    // its own cell.
    for (const [lat, lng] of [
      [90, 180], [90, 0], [90, -73], [0, 180], [45, 180], [-90, 180], [90, -180],
    ] as const) {
      const cell = decodeGeohash(encodeGeohash(lat, lng, 4));
      expect(cell, `${lat},${lng}`).not.toBeNull();
      if (!cell) continue;
      expect(geohashCellContains(cell, P(lat, lng)), `${lat},${lng} not in its own cell`).toBe(true);
    }
  });

  it("contains a point at the bottom of the domain too, which always worked", () => {
    // The min edges are inclusive, which is why -90/-180 passed and hid the case above.
    for (const [lat, lng] of [[-90, -180], [-90, 0], [0, -180]] as const) {
      const cell = decodeGeohash(encodeGeohash(lat, lng, 4));
      expect(cell).not.toBeNull();
      if (!cell) continue;
      expect(geohashCellContains(cell, P(lat, lng)), `${lat},${lng}`).toBe(true);
    }
  });

  it("closing the top edge does not make cells overlap", () => {
    // The fix must not break tiling. A point on an INTERIOR max edge still belongs to exactly one
    // cell - the one above it - so only the domain boundary is closed.
    const cell = decodeGeohash("u4pr");
    expect(cell).not.toBeNull();
    if (!cell) return;
    expect(cell.lat.max).not.toBe(90);
    expect(cell.lng.max).not.toBe(180);
    // Its own top-edge points belong to the NEXT cell, not to it.
    expect(geohashCellContains(cell, P(cell.lat.max, cell.center.lng))).toBe(false);
    expect(geohashCellContains(cell, P(cell.center.lat, cell.lng.max))).toBe(false);
  });

  it("every point belongs to exactly one cell across a sweep that includes the boundaries", () => {
    // An exhaustive one-cell-only check over a coarse precision, boundaries included. Precision 2
    // keeps the cell count small enough to enumerate all of them per point.
    const allHashes: string[] = [];
    for (const a of GEOHASH_BASE32) for (const b of GEOHASH_BASE32) allHashes.push(a + b);
    const cells = allHashes.map((h) => decodeGeohash(h)).filter((c): c is NonNullable<typeof c> => !!c);
    expect(cells).toHaveLength(1024);

    for (const [lat, lng] of [
      [90, 180], [-90, -180], [90, -180], [-90, 180], [0, 0], [0, 180], [0, -180],
      [90, 0], [-90, 0], [51.5074, -0.1278], [1.3521, 103.8198], [-33.86, 151.21],
    ] as const) {
      const hits = cells.filter((c) => geohashCellContains(c, P(lat, lng)));
      expect(hits, `${lat},${lng} landed in ${hits.length} cells`).toHaveLength(1);
      // And it is the cell `encodeGeohash` names.
      expect(hits[0]?.hash).toBe(encodeGeohash(lat, lng, 2));
    }
  });

  it("cells at one precision tile the globe without gaps or overlaps", () => {
    // `geohashCellContains` is inclusive-min / exclusive-max so adjacent cells abut exactly. If it
    // were inclusive on both, a point on a boundary would be in two cells.
    for (let i = 0; i < 300; i += 1) {
      const point = P(-89 + (178 * i) / 300, -179 + (358 * ((i * 7) % 300)) / 300);
      const own = decodeGeohash(encodeGeohash(point.lat, point.lng, 4));
      expect(own).not.toBeNull();
      if (!own) continue;
      expect(geohashCellContains(own, point)).toBe(true);
    }
  });
});

describe("geohash - the coarsening property later slices depend on", () => {
  it("a shorter prefix names a strictly larger cell containing the longer one", () => {
    const fine = decodeGeohash("u4pruyd");
    const coarse = decodeGeohash("u4pr");
    expect(fine).not.toBeNull();
    expect(coarse).not.toBeNull();
    if (!fine || !coarse) return;
    expect(coarse.widthKm).toBeGreaterThan(fine.widthKm);
    expect(coarse.heightKm).toBeGreaterThan(fine.heightKm);
    expect(fine.lat.min).toBeGreaterThanOrEqual(coarse.lat.min);
    expect(fine.lat.max).toBeLessThanOrEqual(coarse.lat.max);
    expect(fine.lng.min).toBeGreaterThanOrEqual(coarse.lng.min);
    expect(fine.lng.max).toBeLessThanOrEqual(coarse.lng.max);
  });

  it("two nearby points share a coarse prefix but differ at fine precision", () => {
    // The basis of prefix sharding - and the reason sharding leaks: sharing a prefix IS revealing
    // the cell you are in.
    const a = P(1.3521, 103.8198);
    const b = P(1.3555, 103.8225);
    expect(encodeGeohash(a.lat, a.lng, 4)).toBe(encodeGeohash(b.lat, b.lng, 4));
    expect(encodeGeohash(a.lat, a.lng, 9)).not.toBe(encodeGeohash(b.lat, b.lng, 9));
  });
});
