import { describe, expect, it } from "vitest";
import { haversineKm, withinRadiusKm, MAX_DISTANCE_KM } from "../src/geo/distance";
import fixture from "./fixtures/geo-parity.json";

/**
 * Parity with the DEPRECATED server-side `near=` filter.
 *
 * This is the test that makes the deprecation a safe behaviour-preserving change rather than a
 * silent one: the on-device filter must admit exactly the providers the server-side one did.
 *
 * WHERE THE EXPECTED VALUES COME FROM, which is the whole design of this file. The fixture is
 * generated by the REAL Rust - `cargo test -p admin-api -- --ignored --nocapture
 * print_geo_parity_fixture` runs `stacks/admin/api/src/routes.rs::haversine_km` over the case list
 * and prints what it actually produces, including its admit/reject decision at each radius. A
 * hand-written TypeScript port as the oracle would only have proved the port self-consistent with
 * itself, which is the "test the stand-in, not the thing" trap. The same fixture is asserted from
 * the Rust side by `geo_parity_fixture_is_what_this_haversine_actually_produces`, so neither end can
 * drift without a red test naming the regeneration command. Same shape as `clientHandoffIcs.test.ts`
 * pinning the `.ics` bytes from both ends.
 *
 * THE CLAIM IS ABOUT INCLUSION SETS, not about equal distances, and the difference matters. The
 * deprecated `asin(sqrt(a))` form returns NaN for some near-antipodal pairs, and `NaN <= radius` is
 * `false`, so it silently drops those providers. The total `atan2` form used here returns the
 * half-circumference instead. Both therefore EXCLUDE such a provider at every radius below
 * ~20015 km - the sets agree - and they can only differ for a planet-spanning radius, which no
 * caller of a "nearby vets" feature has.
 */

interface FixtureCase {
  name: string;
  from: [number, number];
  to: [number, number];
  /** `null` means the deprecated Rust returns NaN for this pair. */
  serverKm: number | null;
  admits: boolean[];
}
interface Fixture {
  earthRadiusKm: number;
  radiiKm: number[];
  cases: FixtureCase[];
}

const fx = fixture as unknown as Fixture;
const at = <T,>(xs: readonly T[], i: number): T => {
  const v = xs[i];
  if (v === undefined) throw new Error(`fixture index ${i} missing`);
  return v;
};
const pt = (p: [number, number]) => ({ lat: at(p, 0), lng: at(p, 1) });

describe("geo parity fixture", () => {
  it("is present and non-trivial", () => {
    // A fixture that silently emptied would make every assertion below vacuous.
    expect(fx.cases.length).toBeGreaterThanOrEqual(18);
    expect(fx.radiiKm.length).toBeGreaterThanOrEqual(5);
    expect(fx.earthRadiusKm).toBe(6371);
  });

  it("covers the cases that actually bite", () => {
    const names = new Set(fx.cases.map((c) => c.name));
    for (const required of [
      "identical_points_equator",
      "one_degree_lon_at_equator",
      "one_degree_lon_at_lat_60",
      "antimeridian_short_hop",
      "north_pole_to_equator",
      "south_pole_to_equator",
      "exact_antipode_equator",
      "near_antipode_nan",
    ]) {
      expect(names, `fixture lost coverage of ${required}`).toContain(required);
    }
  });
});

describe("haversineKm reproduces the deprecated server distance", () => {
  for (const c of fx.cases) {
    if (c.serverKm === null) continue; // the NaN case has its own test below
    it(`${c.name}`, () => {
      const got = haversineKm(pt(c.from), pt(c.to));
      // Both languages evaluate the same IEEE 754 doubles but their `sin`/`cos` can disagree in the
      // last ulp, and the two formulas are algebraically equal rather than bitwise identical. 1e-9
      // relative is ~1 micrometre at city scale and ~20 micrometres at planetary scale - far tighter
      // than anything that could change an admission decision.
      expect(Math.abs(got - c.serverKm)).toBeLessThanOrEqual(1e-9 * Math.max(1, Math.abs(c.serverKm)));
    });
  }
});

describe("withinRadiusKm admits exactly what the server-side filter admitted", () => {
  for (const c of fx.cases) {
    it(`${c.name}`, () => {
      fx.radiiKm.forEach((radius, i) => {
        expect(
          withinRadiusKm(pt(c.from), pt(c.to), radius),
          `${c.name} at radius ${radius} km`,
        ).toBe(at(c.admits, i));
      });
    });
  }
});

describe("the one divergence, stated rather than hidden", () => {
  const nanCase = fx.cases.find((c) => c.serverKm === null);

  it("the fixture records a pair the deprecated filter could not compute", () => {
    // If this disappears, the divergence below is no longer being exercised and the parity claim
    // silently narrows to "the cases that happened to work".
    expect(nanCase, "fixture no longer carries a NaN case").toBeDefined();
  });

  it("returns the half-circumference where the deprecated form returned NaN", () => {
    if (!nanCase) return;
    const got = haversineKm(pt(nanCase.from), pt(nanCase.to));
    expect(Number.isNaN(got)).toBe(false);
    expect(got).toBeCloseTo(MAX_DISTANCE_KM, 6);
  });

  it("still excludes that pair at every radius the fixture tests, exactly as the server did", () => {
    if (!nanCase) return;
    // This is what makes the divergence harmless: `NaN <= r` was false, and `20015.09 <= r` is also
    // false for every r below the half-circumference. Same answer, arrived at honestly.
    fx.radiiKm.forEach((radius, i) => {
      expect(at(nanCase.admits, i)).toBe(false);
      expect(withinRadiusKm(pt(nanCase.from), pt(nanCase.to), radius)).toBe(false);
    });
  });

  it("only diverges above the half-circumference", () => {
    if (!nanCase) return;
    const beyond = MAX_DISTANCE_KM + 1;
    // The deprecated filter rejects at ANY radius, because NaN never compares true. Ours admits,
    // because the two points really are ~20015 km apart and that is within the stated radius.
    expect(withinRadiusKm(pt(nanCase.from), pt(nanCase.to), beyond)).toBe(true);
  });
});

describe("no fixture pair can produce NaN through the on-device filter", () => {
  it("every case yields a finite distance", () => {
    for (const c of fx.cases) {
      const got = haversineKm(pt(c.from), pt(c.to));
      expect(Number.isFinite(got), `${c.name} produced ${got}`).toBe(true);
    }
  });
});
