#!/usr/bin/env bash
# Print the ADDRESS CONFIGURATION for one stack, resolved from the deploy ledger.
#
#   scripts/gen-deployment-env.sh vet          > stacks/vet/.env.addresses
#   scripts/gen-deployment-env.sh vet-web      >> stacks/vet/web/.env
#   scripts/gen-deployment-env.sh --list
#
# WHY THIS EXISTS
#
# Every `.env.example` in this repo now ships its addresses BLANK, because a value in a template opts
# every deployment that copies it into reading a set nobody chose for it. That is the right default,
# and on its own it moves the work to a human: read ten addresses out of a JSON file and paste them
# into the right variables, per stack, after every redeploy. Pasting is exactly how a wrong address
# gets in, and a wrong address is silent - it compiles, it connects, and it keeps answering until
# somebody notices a verdict that makes no sense.
#
# So the DEPLOY writes the configuration. `contracts/deployments/roax.json` is written by
# `contracts/script/Deploy.s.sol`; this script is the projection of it onto each stack's variable
# names. A redeploy is: run Deploy, re-run this, restart. Nothing is transcribed by hand.
#
# WHAT IT DOES NOT DO
#
# It writes no file and edits nothing - it prints to stdout, so the operator decides where the values
# land and can diff them against what a stack is running. It also never invents an address: a key
# missing from the ledger is an ERROR naming the key, never a zero or a placeholder.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=scripts/lib/ledger.sh
source "$ROOT/scripts/lib/ledger.sh"

TARGETS="admin vet groomer government indexer admin-web vet-web groomer-web owner-web mobile"

usage() {
  cat >&2 <<EOF
usage: $(basename "$0") <target>

targets: $TARGETS

Prints the address configuration for that stack, resolved from
contracts/deployments/roax.json by KEY NAME.
EOF
  exit 2
}

[ $# -eq 1 ] || usage
case "$1" in --list|-l) echo "$TARGETS"; exit 0 ;; -h|--help) usage ;; esac

CHAIN_ID="$(ledger_chain_id)"
[ -n "$CHAIN_ID" ] || { echo "ERROR: the ledger declares no chainId" >&2; exit 1; }

# Resolve every address ONCE, up front, so a missing key fails before anything is printed. A partial
# block is worse than no block: half of it looks configured.
PROVIDER_REGISTRY="$(ledger_require ProviderRegistry)"
FACTORY="$(ledger_require DogTagIssuerFactory)"
ISSUER_IMPL="$(ledger_require DogTagIssuerImpl)"
SBT="$(ledger_require DogTagSBTConsent)"
VERIFIER="$(ledger_require Groth16VerifierConsent)"
VREG="$(ledger_require VerificationRegistryConsent)"
DIRECTORY="$(ledger_require ProviderDirectory)"
DOMAIN_RESOLVER="$(ledger_require ServiceDomainResolver)"
PROTOCOL_REGISTRY="$(ledger_require ProtocolRegistry)"
ADMIN_SIGNER="$(ledger_require admin)"

banner() {
  echo "# Generated by scripts/gen-deployment-env.sh from contracts/deployments/roax.json."
  echo "# Do not hand-edit: re-run after every deploy. chainId $CHAIN_ID."
}

# The web block is identical across the portals that consume `packages/ui`, because they read the
# same `DEPLOYED_ADDRESSES`. Kept in one function so the three can never drift.
portal_block() {
  echo "VITE_PROVIDER_REGISTRY_ADDR=$PROVIDER_REGISTRY"
  echo "VITE_DOGTAG_ISSUER_FACTORY_ADDR=$FACTORY"
  echo "VITE_DOGTAG_ISSUER_IMPL_ADDR=$ISSUER_IMPL"
  echo "VITE_DOGTAG_SBT_CONSENT_ADDR=$SBT"
  echo "VITE_VERIFICATION_REGISTRY_CONSENT_ADDR=$VREG"
  echo "VITE_GROTH16_VERIFIER_CONSENT_ADDR=$VERIFIER"
  echo "VITE_PROTOCOL_REGISTRY_ADDR=$PROTOCOL_REGISTRY"
  echo "VITE_PROVIDER_DIRECTORY_ADDR=$DIRECTORY"
  echo "VITE_SERVICE_DOMAIN_RESOLVER_ADDR=$DOMAIN_RESOLVER"
  echo "VITE_ADMIN_SIGNER_ADDR=$ADMIN_SIGNER"
}

banner
case "$1" in
  admin)
    echo "CHAIN_ID=$CHAIN_ID"
    echo "PROVIDER_REGISTRY_ADDR=$PROVIDER_REGISTRY"
    echo "FACTORY_ADDR=$FACTORY"
    echo "SBT_ADDR=$SBT"
    echo "VERIFICATION_REGISTRY_ADDR=$VREG"
    ;;
  vet|groomer)
    echo "CHAIN_ID=$CHAIN_ID"
    echo "FACTORY_ADDR=$FACTORY"
    echo "VERIFICATION_REGISTRY_CONSENT_ADDR=$VREG"
    echo "SBT_CONSENT_ADDR=$SBT"
    # The on-chain VK identity. Read by the signed-manifest serving path
    # (`protocol::deployment_from_env`), which mirrors the published record and refuses to serve
    # rather than guess a member. These five names ARE `protocol::DEPLOYMENT_ENV`.
    echo "GROTH16_VERIFIER_CONSENT_ADDR=$VERIFIER"
    # Deliberately NOT emitted: PROFILE_ISSUER_ADDR / VACCINATION_ISSUER_ADDR. Those are per-provider
    # DogTagIssuer CLONES, deployed by a provider rather than by Deploy.s.sol, so the ledger holds no
    # key for them and inventing one would name a contract that does not exist.
    ;;
  government)
    echo "CHAIN_ID=$CHAIN_ID"
    echo "FACTORY_ADDR=$FACTORY"
    echo "VERIFICATION_REGISTRY_ADDR=$VREG"
    # TRAVEL_CLEARANCE_ISSUER_ADDR / EU_HEALTH_CERT_ISSUER_ADDR are clones too - see above.
    ;;
  indexer)
    echo "CHAIN_ID=$CHAIN_ID"
    # ONE atomic object: the triple and its seed clones travel together, so list ordering cannot
    # cross-wire two deployments. Empty seedClones is a complete statement - discover every clone
    # from IssuerCreated.
    #
    # NOTE the second member is the PROVIDER AUTHORITY. The variable is still spelled
    # `issuerRegistry` on the wire because that is the shape the indexer parses; what it names is
    # whichever contract emits the capability grants this generation records.
    printf 'INDEXER_GENERATIONS=[{"factory":"%s","issuerRegistry":"%s","verificationRegistry":"%s","seedClones":[]}]\n' \
      "$FACTORY" "$PROVIDER_REGISTRY" "$VREG"
    ;;
  admin-web|vet-web|groomer-web)
    portal_block
    ;;
  owner-web)
    # The holder wallet reads exactly one address: the sole emitter of the owner-blind `Verified`
    # events its consent history scans.
    echo "VITE_VERIFICATION_REGISTRY_CONSENT_ADDR=$VREG"
    ;;
  mobile)
    # The phones bundle ONE address - the discovery anchor - plus the chain id and the bundled RPC.
    # Everything else (factory, verification registry, SBT, verifier, provider registry) is resolved
    # from `getDiscoverySet` at RUNTIME, which is the property the anchor exists for: the app CHECKS
    # a platform's version claim instead of trusting it.
    #
    # This target prints for a human; `scripts/gen-mobile-roax-config.sh` writes the bundles.
    echo "chainId=$CHAIN_ID"
    echo "ProtocolRegistry=$PROTOCOL_REGISTRY"
    ;;
  *) usage ;;
esac
