//! On-device Groth16 proving (Workstream A) — UniFFI surface, gated behind the `prover` feature.
//!
//! This module lets the mobile app generate the verification Groth16 proof **locally** (true ZK):
//! the groomer never sees the raw record, only relays `{proof, publicSignals, consent}` on-chain.
//!
//! It MIRRORS the ark-0.6 backend prover (`crates/dogtag-prover-rs/src/lib.rs`
//! `push_named_inputs` + `format_output`) but does NOT depend on it — the backend stays on ark 0.6,
//! this crate stays on ark 0.5. Here we use `circom-prover` (ark 0.5 / mopro) + `rust-witness`
//! (wasm2c witness, no wasmer) over the vendored `circuit/verification.wasm`.
//!
//! The circuit `DogTagVerification(24, 5)` takes 19 named inputs and emits 7 public outputs in the
//! snarkjs order `[dogTagId, purpose, relayer, subject, nullifier, keyHash, R]`. We ASSEMBLE all 19
//! inputs from this crate's own internals (wrap/leaf/field/merkle) + the passed-through EdDSA sig,
//! prove, then format the proof with the snarkjs->Solidity b-coordinate swap so the calldata drops
//! straight into `recordVerificationZK`.

use std::collections::HashMap;

use ark_bn254::Fr;
use ark_ff::PrimeField;
use num_bigint::BigInt;
use serde_json::Value;

use circom_prover::{
    prover::ProofLib,
    witness::WitnessFn,
    CircomProver,
};

use crate::consent::VerificationConsent;
use crate::ffi::FfiError;
use crate::field::{field_from_scalar_bytes, to_hex32};
use crate::leaf::{field_of_keypath, field_of_value, hash_leaf};
use crate::merkle::build_merkle;
use crate::types::{TypeTag, TypedScalar};
use crate::wrap::{flatten_data, parse_packed, scalar_from_packed, WrappedDoc};

/// `N` — the circuit's max leaf width (`DogTagVerification(24, 5)`).
const N: usize = 24;
/// Number of public signals the circuit exposes.
const NUM_PUBLIC: usize = 7;
/// The canonical key path of the dogTagId leaf (bound by the circuit via `dogTagKeyPathField`).
const DOG_TAG_KEY_PATH: &str = "credentialSubject.dogTagId";

// Link the wasm2c witness calculator generated by build.rs for `circuit/verification.wasm`.
// This yields `verification_witness`, the `WitnessFn::RustWitness` fn circom-prover consumes.
rust_witness::witness!(verification);

/// The pass-through EdDSA-BabyJubjub consent signature + public key (decimal scalars + hex point).
///
/// `r8x_dec` / `r8y_dec` / `s_dec` come from `sign_consent_eddsa` (ffi.rs `EddsaSignatureFfi`);
/// `ax_hex` / `ay_hex` are the consent public point (0x.. 32-byte BE field hex).
#[derive(uniffi::Record)]
pub struct EddsaSigInput {
    pub r8x_dec: String,
    pub r8y_dec: String,
    pub s_dec: String,
    pub ax_hex: String,
    pub ay_hex: String,
}

/// A Groth16 proof formatted exactly as the on-chain Solidity calldata expects (mirrors
/// `dogtag-prover-rs::Groth16Output`): `a`/`c` are G1 `[x,y]`; `b` is G2 with the snarkjs->Solidity
/// coordinate swap applied (`b[0]=[bx_c1,bx_c0]`, `b[1]=[by_c1,by_c0]`); `pub_signals` is the
/// 7-element output vector. All values are base-10 decimal strings.
#[derive(uniffi::Record)]
pub struct ProofFfi {
    pub a: Vec<String>,
    pub b: Vec<Vec<String>>,
    pub c: Vec<String>,
    pub pub_signals: Vec<String>,
}

fn err<E: std::fmt::Display>(e: E) -> FfiError {
    FfiError::Invalid(e.to_string())
}

/// Convert a field element to its base-10 decimal string.
fn fe_to_dec(f: &Fr) -> String {
    f.into_bigint().to_string()
}

/// Parse a 0x.. 32-byte BE hex into a field element.
fn field_from_hex(label: &str, h: &str) -> Result<Fr, FfiError> {
    let s = h.strip_prefix("0x").unwrap_or(h);
    let bytes = hex::decode(s).map_err(|e| err(format!("bad {label} hex: {e}")))?;
    if bytes.len() != 32 {
        return Err(FfiError::Invalid(format!(
            "{label} hex must be 32 bytes (got {})",
            bytes.len()
        )));
    }
    Ok(Fr::from_be_bytes_mod_order(&bytes))
}

/// Decode a 0x.. hex string into exactly `M` bytes (BE word / address).
fn decode_word<const M: usize>(label: &str, h: &str) -> Result<[u8; M], FfiError> {
    let s = h.strip_prefix("0x").unwrap_or(h);
    let bytes = hex::decode(s).map_err(|e| err(format!("bad {label} hex: {e}")))?;
    if bytes.len() != M {
        return Err(FfiError::Invalid(format!(
            "{label} must be {M} bytes (got {})",
            bytes.len()
        )));
    }
    let mut out = [0u8; M];
    out.copy_from_slice(&bytes);
    Ok(out)
}

/// Parse the consent JSON (same shape as ffi.rs `consent_from_hex` / the POSTed consent) into a
/// `VerificationConsent`. Fields are 0x.. hex: uint256/bytes32 are 32-byte BE, addresses 20-byte.
fn consent_from_json(consent: &Value) -> Result<VerificationConsent, FfiError> {
    let s = |k: &str| -> Result<String, FfiError> {
        consent
            .get(k)
            .and_then(|v| v.as_str())
            .map(|v| v.to_string())
            .ok_or_else(|| FfiError::Invalid(format!("consent.{k}: missing or not a string")))
    };
    Ok(VerificationConsent {
        dog_tag_id: decode_word::<32>("dogTagId", &s("dogTagId")?)?,
        record_type: decode_word::<32>("recordType", &s("recordType")?)?,
        purpose: decode_word::<32>("purpose", &s("purpose")?)?,
        credential_root: decode_word::<32>("credentialRoot", &s("credentialRoot")?)?,
        challenge: decode_word::<32>("challenge", &s("challenge")?)?,
        relayer: decode_word::<20>("relayer", &s("relayer")?)?,
        subject: decode_word::<20>("subject", &s("subject")?)?,
        nonce: decode_word::<32>("nonce", &s("nonce")?)?,
        deadline: decode_word::<32>("deadline", &s("deadline")?)?,
    })
}

/// The 19 assembled circuit inputs (all decimal-string field elements; arrays of width `N`).
/// Mirrors `dogtag-prover-rs::ProveInputs` field-for-field so the input contract is identical.
struct AssembledInputs {
    dog_tag_id: String,
    purpose: String,
    relayer: String,
    subject: String,
    num_leaves: String,
    leaf_key_path_hashes: [String; N],
    leaf_type_tags: [String; N],
    leaf_salts: [String; N],
    leaf_values: [String; N],
    dog_tag_id_leaf_index: String,
    sorted_leaf_hashes: [String; N],
    perm: [String; N],
    dog_tag_key_path_field: String,
    consent_nonce: String,
    ax: String,
    ay: String,
    r8x: String,
    r8y: String,
    s: String,
    /// The merkle root over the active leaves (== credentialRoot, asserted by caller). Read by the
    /// assembler parity test.
    #[allow(dead_code)]
    root: Fr,
}

/// Per-leaf assembled fields in canonical (flatten) order.
struct LeafFields {
    key_path_hash: Fr,
    type_tag: u8,
    salt_field: Fr,
    value_field: Fr,
    /// The full leaf hash = Poseidon(DS_LEAF, kp, salt, tag, value).
    hash: Fr,
}

/// Assemble all 19 circuit inputs from the wrapped doc, consent, and EdDSA signature.
///
/// MIRRORS `circuits/scripts/gen-zk-fixture.mjs` + `dogtag-prover-rs::push_named_inputs` ordering:
/// per-leaf fields in canonical flatten order; `sortedLeafHashes` = the ascending-sorted active
/// prefix (`merkle::build_merkle(active).layers[0]`); `perm[k]` = index in the canonical active
/// order of `sortedLeafHashes[k]`; padding slots `[numLeaves, N)` pinned diagonal (`perm[k]=k`,
/// dummy leaf). Asserts `root == credentialRoot` and `numLeaves <= N`.
fn assemble(
    doc: &WrappedDoc,
    consent: &VerificationConsent,
    sig: &EddsaSigInput,
) -> Result<AssembledInputs, FfiError> {
    // 1. Canonical-ordered (keyPath, packed) pairs (same order verify/wrap use).
    let pairs = flatten_data(&doc.data);
    let num_leaves = pairs.len();
    if num_leaves == 0 {
        return Err(FfiError::Invalid("wrapped doc has no leaves".into()));
    }
    if num_leaves > N {
        return Err(FfiError::Invalid(format!(
            "too many leaves: {num_leaves} > N={N}"
        )));
    }

    // 2. Per-leaf assembled fields in canonical order + the dogTagId leaf index.
    let mut leaves: Vec<LeafFields> = Vec::with_capacity(num_leaves);
    let mut dog_tag_id_leaf_index: Option<usize> = None;
    for (i, (key_path, packed)) in pairs.iter().enumerate() {
        let (salt_hex, tag, value_rest) = parse_packed(packed).map_err(FfiError::from)?;
        let salt = hex::decode(&salt_hex).map_err(|e| err(format!("bad salt hex: {e}")))?;
        if salt.len() != 16 {
            return Err(FfiError::Invalid(format!(
                "salt must be 16 bytes (got {})",
                salt.len()
            )));
        }
        let scalar: TypedScalar = scalar_from_packed(tag, &value_rest).map_err(FfiError::from)?;
        let hash = hash_leaf(key_path, &salt, &scalar).map_err(FfiError::from)?;
        leaves.push(LeafFields {
            key_path_hash: field_of_keypath(key_path),
            type_tag: tag as u8,
            salt_field: field_from_scalar_bytes(&salt),
            value_field: field_of_value(&scalar).map_err(FfiError::from)?,
            hash,
        });
        if key_path == DOG_TAG_KEY_PATH {
            dog_tag_id_leaf_index = Some(i);
        }
    }
    let dog_tag_id_leaf_index = dog_tag_id_leaf_index.ok_or_else(|| {
        FfiError::Invalid(format!("missing required leaf {DOG_TAG_KEY_PATH}"))
    })?;

    // 3. Merkle tree over the ACTIVE leaves (the canonical-order hashes). The SDK sorts ascending
    //    and folds bottom-up; layers[0] is the ascending-sorted leaf order = sortedLeafHashes.
    let active_hashes: Vec<Fr> = leaves.iter().map(|l| l.hash).collect();
    let tree = build_merkle(&active_hashes);
    let sorted_active = &tree.layers[0];
    let root = tree.root;

    // 3a. Assert the tree root == the consent's credentialRoot (defensive — circuit also binds R).
    let consent_root = Fr::from_be_bytes_mod_order(&consent.credential_root);
    if root != consent_root {
        return Err(FfiError::Invalid(format!(
            "merkle root {} != consent.credentialRoot {}",
            to_hex32(&root),
            to_hex32(&consent_root)
        )));
    }

    // 4. Build the N-wide arrays. Active prefix [0, numLeaves): canonical-order leaf fields, with
    //    sortedLeafHashes = sorted active order and perm[k] = canonical index of sortedActive[k].
    //    Padding slots [numLeaves, N): a dummy diagonal leaf (perm[k]=k, active[k]=0 in-circuit).
    let mut leaf_key_path_hashes: [String; N] = Default::default();
    let mut leaf_type_tags: [String; N] = Default::default();
    let mut leaf_salts: [String; N] = Default::default();
    let mut leaf_values: [String; N] = Default::default();
    let mut sorted_leaf_hashes: [String; N] = Default::default();
    let mut perm: [String; N] = Default::default();

    // A deterministic dummy leaf hash for the padding slots (value never affects the proof because
    // the circuit gates each slot by active[k] = (k < numLeaves); we just need a valid field el).
    let dummy = hash_leaf(
        "__pad__",
        &[0u8; 16],
        &TypedScalar::Integer("0".to_string()),
    )
    .map_err(FfiError::from)?;
    let dummy_kp = field_of_keypath("__pad__");
    let dummy_tag = TypeTag::Integer as u8;
    let dummy_salt = field_from_scalar_bytes(&[0u8; 16]);
    let dummy_val = field_of_value(&TypedScalar::Integer("0".to_string())).map_err(FfiError::from)?;

    for k in 0..N {
        if k < num_leaves {
            let lf = &leaves[k];
            leaf_key_path_hashes[k] = fe_to_dec(&lf.key_path_hash);
            leaf_type_tags[k] = (lf.type_tag as u64).to_string();
            leaf_salts[k] = fe_to_dec(&lf.salt_field);
            leaf_values[k] = fe_to_dec(&lf.value_field);

            let sorted = sorted_active[k];
            sorted_leaf_hashes[k] = fe_to_dec(&sorted);
            // perm[k] = canonical index of the sorted leaf (findIndex in the active prefix).
            let idx = active_hashes
                .iter()
                .position(|h| *h == sorted)
                .expect("sorted leaf must exist in active set");
            perm[k] = idx.to_string();
        } else {
            // Diagonal padding slot.
            leaf_key_path_hashes[k] = fe_to_dec(&dummy_kp);
            leaf_type_tags[k] = (dummy_tag as u64).to_string();
            leaf_salts[k] = fe_to_dec(&dummy_salt);
            leaf_values[k] = fe_to_dec(&dummy_val);
            sorted_leaf_hashes[k] = fe_to_dec(&dummy);
            perm[k] = k.to_string();
        }
    }

    // 5. Scalars from the consent (decimal field elements; addresses as uint160).
    let dog_tag_id = fe_to_dec(&Fr::from_be_bytes_mod_order(&consent.dog_tag_id));
    let purpose = fe_to_dec(&Fr::from_be_bytes_mod_order(&consent.purpose));
    let relayer = fe_to_dec(&Fr::from_be_bytes_mod_order(&consent.relayer));
    let subject = fe_to_dec(&Fr::from_be_bytes_mod_order(&consent.subject));
    let consent_nonce = fe_to_dec(&Fr::from_be_bytes_mod_order(&consent.nonce));

    // 6. dogTagKeyPathField — fieldOf(canonical dogTagId key path), bound by the circuit.
    let dog_tag_key_path_field = fe_to_dec(&field_of_keypath(DOG_TAG_KEY_PATH));

    // 7. EdDSA Ax/Ay (hex -> decimal field) + R8x/R8y/S (already decimal).
    let ax = fe_to_dec(&field_from_hex("Ax", &sig.ax_hex)?);
    let ay = fe_to_dec(&field_from_hex("Ay", &sig.ay_hex)?);
    // R8x/R8y/S are pass-through decimal strings; validate they parse as integers.
    let r8x = parse_dec("R8x", &sig.r8x_dec)?;
    let r8y = parse_dec("R8y", &sig.r8y_dec)?;
    let s = parse_dec("S", &sig.s_dec)?;

    Ok(AssembledInputs {
        dog_tag_id,
        purpose,
        relayer,
        subject,
        num_leaves: num_leaves.to_string(),
        leaf_key_path_hashes,
        leaf_type_tags,
        leaf_salts,
        leaf_values,
        dog_tag_id_leaf_index: dog_tag_id_leaf_index.to_string(),
        sorted_leaf_hashes,
        perm,
        dog_tag_key_path_field,
        consent_nonce,
        ax,
        ay,
        r8x,
        r8y,
        s,
        root,
    })
}

/// Validate that `value` is a base-10 integer string, returning it unchanged.
fn parse_dec(field: &str, value: &str) -> Result<String, FfiError> {
    value
        .parse::<BigInt>()
        .map_err(|e| FfiError::Invalid(format!("{field}: not a decimal integer: {e}")))?;
    Ok(value.to_string())
}

/// Build the circom-prover input map (signal name -> decimal-string values), matching the circuit's
/// named inputs and ordering in `push_named_inputs`.
fn input_map(inp: &AssembledInputs) -> HashMap<String, Vec<String>> {
    let mut m: HashMap<String, Vec<String>> = HashMap::new();
    m.insert("dogTagId".into(), vec![inp.dog_tag_id.clone()]);
    m.insert("purpose".into(), vec![inp.purpose.clone()]);
    m.insert("relayer".into(), vec![inp.relayer.clone()]);
    m.insert("subject".into(), vec![inp.subject.clone()]);
    m.insert("numLeaves".into(), vec![inp.num_leaves.clone()]);
    m.insert("leafKeyPathHashes".into(), inp.leaf_key_path_hashes.to_vec());
    m.insert("leafTypeTags".into(), inp.leaf_type_tags.to_vec());
    m.insert("leafSalts".into(), inp.leaf_salts.to_vec());
    m.insert("leafValues".into(), inp.leaf_values.to_vec());
    m.insert(
        "dogTagIdLeafIndex".into(),
        vec![inp.dog_tag_id_leaf_index.clone()],
    );
    m.insert("sortedLeafHashes".into(), inp.sorted_leaf_hashes.to_vec());
    m.insert("perm".into(), inp.perm.to_vec());
    m.insert(
        "dogTagKeyPathField".into(),
        vec![inp.dog_tag_key_path_field.clone()],
    );
    m.insert("consentNonce".into(), vec![inp.consent_nonce.clone()]);
    m.insert("Ax".into(), vec![inp.ax.clone()]);
    m.insert("Ay".into(), vec![inp.ay.clone()]);
    m.insert("R8x".into(), vec![inp.r8x.clone()]);
    m.insert("R8y".into(), vec![inp.r8y.clone()]);
    m.insert("S".into(), vec![inp.s.clone()]);
    m
}

/// Generate a Groth16 proof for the DogTag verification circuit ON DEVICE.
///
/// - `wrapped_doc_json` — the stored WrappedDoc (raw salted leaves; the witness source).
/// - `consent_json`     — the signed consent (same hex shape as the POSTed consent / ffi.rs consent).
/// - `eddsa_sig`        — the EdDSA-BabyJubjub consent signature + public key.
/// - `zkey_path`        — filesystem path to `verification_final.zkey` (bundled app asset).
///
/// Returns the proof as Solidity calldata (`a`, `b` with the snarkjs->Solidity swap, `c`) plus the
/// 7 public signals `[dogTagId, purpose, relayer, subject, nullifier, keyHash, R]` (all decimal).
#[uniffi::export]
pub fn prove_verification(
    wrapped_doc_json: String,
    consent_json: String,
    eddsa_sig: EddsaSigInput,
    zkey_path: String,
) -> Result<ProofFfi, FfiError> {
    let doc: WrappedDoc = serde_json::from_str(&wrapped_doc_json)
        .map_err(|e| err(format!("bad wrapped doc json: {e}")))?;
    let consent_v: Value =
        serde_json::from_str(&consent_json).map_err(|e| err(format!("bad consent json: {e}")))?;
    let consent = consent_from_json(&consent_v)?;

    let inp = assemble(&doc, &consent, &eddsa_sig)?;
    let input_json = serde_json::to_string(&input_map(&inp))
        .map_err(|e| err(format!("serialize circuit input: {e}")))?;

    let proof = CircomProver::prove(
        ProofLib::Arkworks,
        WitnessFn::RustWitness(verification_witness),
        input_json,
        zkey_path,
    )
    .map_err(|e| err(format!("circom-prover prove: {e}")))?;

    // Public signals come back in circuit-output order (snarkjs order). Assert count.
    let pub_signals: Vec<String> = proof.pub_inputs.0.iter().map(|b| b.to_string()).collect();
    if pub_signals.len() != NUM_PUBLIC {
        return Err(FfiError::Invalid(format!(
            "unexpected public-signal count: got {}, expected {NUM_PUBLIC}",
            pub_signals.len()
        )));
    }

    // Format the proof with the snarkjs->Solidity b-coordinate swap (mirrors
    // dogtag-prover-rs::format_output). circom-prover stores G2 as x=[c0,c1]; `as_tuple()` already
    // emits the swapped [c1, c0] form, so we read it directly.
    let (a_t, b_t, c_t) = proof.proof.as_tuple();
    let a = vec![a_t.0.to_string(), a_t.1.to_string()];
    let c = vec![c_t.0.to_string(), c_t.1.to_string()];
    let b = vec![
        vec![b_t.0[0].to_string(), b_t.0[1].to_string()],
        vec![b_t.1[0].to_string(), b_t.1[1].to_string()],
    ];

    Ok(ProofFfi {
        a,
        b,
        c,
        pub_signals,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Build the SAME deterministic input the gen-zk-fixture / tests/gen_input.mjs reference uses
    /// (numLeaves=13, dogTagId=424242, ...) directly in Rust and assert the assembled
    /// sortedLeafHashes / perm / dogTagIdLeafIndex / R match the reference fixture's structure.
    ///
    /// We construct leaves the same way the fixture does — but the FIXTURE uses synthetic numeric
    /// keyPath/salt/value fields directly, whereas our assembler derives them from a WrappedDoc. So
    /// this unit test exercises the assembler's tree/perm logic against an independently-built tree
    /// using the SDK merkle, catching assembly drift without the slow prove.
    #[test]
    fn assembler_tree_and_perm_match_sdk_merkle() {
        use crate::merkle::build_merkle;

        // A small deterministic WrappedDoc with a dogTagId leaf + a few others.
        let doc_json = serde_json::json!({
            "version": "dogtag/1.0",
            "data": {
                "credentialSubject": {
                    "dogTagId": "00000000000000000000000000000001:3:424242",
                    "name": "00000000000000000000000000000002:2:Rex",
                    "breed": "00000000000000000000000000000003:2:Labrador",
                    "microchip": "00000000000000000000000000000004:2:985141006580311"
                }
            },
            "signature": {"type":"DogTagMerkleProof","targetHash":"0x00","proof":[],"merkleRoot":"0x00"},
            "privacy": {"obfuscated": []},
            "issuer": {"name":"V","domain":"v.example","documentStore":"0x0000000000000000000000000000000000000001","recordType":"VACCINATION"}
        });
        let doc: WrappedDoc = serde_json::from_value(doc_json).unwrap();

        // Recompute the active leaves + tree independently from flatten_data.
        let pairs = flatten_data(&doc.data);
        let mut active: Vec<Fr> = Vec::new();
        let mut dog_idx = None;
        for (i, (kp, packed)) in pairs.iter().enumerate() {
            let (salt_hex, tag, val) = parse_packed(packed).unwrap();
            let salt = hex::decode(&salt_hex).unwrap();
            let scalar = scalar_from_packed(tag, &val).unwrap();
            active.push(hash_leaf(kp, &salt, &scalar).unwrap());
            if kp == DOG_TAG_KEY_PATH {
                dog_idx = Some(i);
            }
        }
        let tree = build_merkle(&active);
        let root = tree.root;

        // Build a consent whose credentialRoot == the tree root so assemble() passes its assert.
        let consent_json = serde_json::json!({
            "dogTagId": "0x0000000000000000000000000000000000000000000000000000000000067932",
            "recordType": "0x0000000000000000000000000000000000000000000000000000000000000000",
            "purpose": "0x0000000000000000000000000000000000000000000000000000000000000007",
            "credentialRoot": to_hex32(&root),
            "challenge": "0x0000000000000000000000000000000000000000000000000000000000000000",
            "relayer": "0x1111111111111111111111111111111111111111",
            "subject": "0x7e5f4552091a69125d5dfcb7b8c2659029395bdf",
            "nonce": "0x0000000000000000000000000000000000000000000000000000000000000063",
            "deadline": "0x0000000000000000000000000000000000000000000000000000000000000000"
        });
        let consent = consent_from_json(&consent_json).unwrap();
        let sig = EddsaSigInput {
            r8x_dec: "1".into(),
            r8y_dec: "2".into(),
            s_dec: "3".into(),
            ax_hex: to_hex32(&Fr::from(4u64)),
            ay_hex: to_hex32(&Fr::from(5u64)),
        };

        let asm = assemble(&doc, &consent, &sig).unwrap();

        // numLeaves / dogTagIdLeafIndex
        assert_eq!(asm.num_leaves, pairs.len().to_string());
        assert_eq!(
            asm.dog_tag_id_leaf_index,
            dog_idx.unwrap().to_string(),
            "dogTagIdLeafIndex must be the canonical flatten index"
        );

        // R == tree root
        assert_eq!(asm.root, root);

        // sortedLeafHashes (active prefix) == ascending-sorted active order = layers[0]
        let sorted_active = &tree.layers[0];
        for k in 0..pairs.len() {
            assert_eq!(
                asm.sorted_leaf_hashes[k],
                fe_to_dec(&sorted_active[k]),
                "sortedLeafHashes[{k}] mismatch"
            );
            // perm[k] maps back to the canonical leaf
            let p: usize = asm.perm[k].parse().unwrap();
            assert_eq!(
                active[p], sorted_active[k],
                "perm[{k}] must point at the canonical leaf equal to sortedActive[{k}]"
            );
        }
        // Padding slots pinned diagonal.
        for k in pairs.len()..N {
            assert_eq!(asm.perm[k], k.to_string(), "padding perm[{k}] must be diagonal");
        }
    }

    #[test]
    fn assemble_rejects_root_mismatch() {
        let doc_json = serde_json::json!({
            "version": "dogtag/1.0",
            "data": { "credentialSubject": { "dogTagId": "00000000000000000000000000000001:3:42" } },
            "signature": {"type":"DogTagMerkleProof","targetHash":"0x00","proof":[],"merkleRoot":"0x00"},
            "privacy": {"obfuscated": []},
            "issuer": {"name":"V","domain":"v.example","documentStore":"0x0000000000000000000000000000000000000001","recordType":"VACCINATION"}
        });
        let doc: WrappedDoc = serde_json::from_value(doc_json).unwrap();
        let consent_json = serde_json::json!({
            "dogTagId": "0x000000000000000000000000000000000000000000000000000000000000002a",
            "recordType": "0x0000000000000000000000000000000000000000000000000000000000000000",
            "purpose": "0x0000000000000000000000000000000000000000000000000000000000000007",
            "credentialRoot": "0x0000000000000000000000000000000000000000000000000000000000000001",
            "challenge": "0x0000000000000000000000000000000000000000000000000000000000000000",
            "relayer": "0x1111111111111111111111111111111111111111",
            "subject": "0x7e5f4552091a69125d5dfcb7b8c2659029395bdf",
            "nonce": "0x0000000000000000000000000000000000000000000000000000000000000063",
            "deadline": "0x0000000000000000000000000000000000000000000000000000000000000000"
        });
        let consent = consent_from_json(&consent_json).unwrap();
        let sig = EddsaSigInput {
            r8x_dec: "1".into(), r8y_dec: "2".into(), s_dec: "3".into(),
            ax_hex: to_hex32(&Fr::from(4u64)), ay_hex: to_hex32(&Fr::from(5u64)),
        };
        let res = assemble(&doc, &consent, &sig);
        assert!(res.is_err(), "must reject when root != credentialRoot");
    }
}
