/**
 * Great-circle distance, on the device.
 *
 * WHY THIS EXISTS AT ALL, which is the whole point of the module. The central directory ships a
 * server-side distance filter - `GET /v1/businesses?near=<lat>,<lng>`, on the PUBLIC unauthenticated
 * router - that computes haversine from coordinates the caller supplies. In a product whose premise
 * is that the owner never reveals where they are, the fix is not to authenticate that endpoint: it is
 * to never send the position at all. So the arithmetic moves here, the caller fetches the provider
 * set (which is identical whoever asks for it), and the user's position never becomes a request
 * parameter.
 *
 * That is a boundary, not a preference. Nothing in `geo/` may acquire I/O, and nothing here may turn
 * a position into a query. `sortByDistance` is fine - it is arithmetic over data already held. A
 * `fetchNearby` would defeat the module.
 *
 * WHY `atan2` RATHER THAN `asin`. The server's form ends in `2 * R * asin(sqrt(a))`
 * (`stacks/admin/api/src/routes.rs`). For near-antipodal inputs `a` rounds two ulps above 1.0 in
 * f64, `sqrt` stays above 1, and `asin` outside [-1, 1] is NaN. Measured: roughly 1 in 12,000
 * uniformly-sampled near-antipodal pairs, in BOTH Rust's libm and V8. `NaN <= radius` is `false` in
 * both languages, so the provider is silently dropped - a "could not compute" rendered as a definite
 * "out of range", which is the inverse of the rule this codebase applies everywhere else.
 *
 * `atan2(sqrt(a), sqrt(max(0, 1 - a)))` is total: it returns the half-circumference there instead.
 * The constraint this satisfies is simply that NO input pair may yield NaN.
 *
 * The two therefore admit exactly the same providers for every radius below the half-circumference
 * (~20015 km), and differ only where the server would drop an antipodal provider from a
 * planet-spanning radius. That equivalence is pinned from both ends against one fixture generated by
 * the deprecated Rust itself - `packages/ui/test/geoParity.test.ts` and the parity tests in
 * `stacks/admin/api/src/routes.rs`.
 */

/**
 * Mean Earth radius in kilometres.
 *
 * 6371.0 exactly, matching the deprecated server filter, so the parity claim is about the formula
 * rather than about a constant. (The IUGG mean is 6371.0088; the 8.8 m difference is four orders of
 * magnitude below the GPS fix that will supply the user's position.)
 */
export const EARTH_RADIUS_KM = 6371.0;

/** Half the great-circle circumference - the largest distance two points on the sphere can have. */
export const MAX_DISTANCE_KM = Math.PI * EARTH_RADIUS_KM;

/** A latitude/longitude pair in decimal degrees. */
export interface LatLng {
  lat: number;
  lng: number;
}

const toRad = (deg: number): number => (deg * Math.PI) / 180;

/**
 * Is this a usable position?
 *
 * Both components finite, latitude within ±90, longitude within ±180. Deliberately NOT enforced by
 * `haversineKm`, which stays a total primitive mirroring the server's: the place to reject an
 * unusable coordinate is where it would otherwise be presented to a user as a distance, which is
 * `sortByDistance`.
 */
export function isValidLatLng(p: LatLng | null | undefined): p is LatLng {
  if (!p) return false;
  const { lat, lng } = p;
  return (
    Number.isFinite(lat) &&
    Number.isFinite(lng) &&
    lat >= -90 &&
    lat <= 90 &&
    lng >= -180 &&
    lng <= 180
  );
}

/**
 * Great-circle distance in kilometres between two points.
 *
 * Total: never returns NaN for any finite input, including exact antipodes. Non-finite input in
 * gives non-finite out - see `isValidLatLng` for why validation lives at the call site.
 *
 * Longitude wrapping is handled by the formula rather than by pre-normalising: the difference enters
 * only as `sin²(Δλ/2)`, which is periodic, so a hop across the antimeridian (179.9° to -179.9°) is
 * correctly 0.2° apart rather than 359.8°.
 */
export function haversineKm(a: LatLng, b: LatLng): number {
  const phi1 = toRad(a.lat);
  const phi2 = toRad(b.lat);
  const dPhi = toRad(b.lat - a.lat);
  const dLambda = toRad(b.lng - a.lng);

  const h =
    Math.sin(dPhi / 2) ** 2 +
    Math.cos(phi1) * Math.cos(phi2) * Math.sin(dLambda / 2) ** 2;

  // The total form. `Math.max(0, 1 - h)` guards the other side of the same rounding: `h` can land
  // marginally above 1, which would make `1 - h` negative and `sqrt` NaN.
  return 2 * EARTH_RADIUS_KM * Math.atan2(Math.sqrt(h), Math.sqrt(Math.max(0, 1 - h)));
}

/**
 * Is `b` within `radiusKm` of `a`?
 *
 * The on-device replacement for the deprecated `near=`/`radius=` server filter, with the same
 * inclusive `<=` boundary. An unusable coordinate on either side is NOT within any radius - a
 * position we cannot evaluate must not be admitted, and must not be reported as distance 0.
 */
export function withinRadiusKm(a: LatLng, b: LatLng, radiusKm: number): boolean {
  if (!isValidLatLng(a) || !isValidLatLng(b)) return false;
  if (!Number.isFinite(radiusKm) || radiusKm < 0) return false;
  return haversineKm(a, b) <= radiusKm;
}

/** One item paired with its computed distance. `distanceKm` is `null` when it has no usable position. */
export interface Ranked<T> {
  item: T;
  /** Kilometres from the origin, or `null` when the item's position was missing or unusable. */
  distanceKm: number | null;
}

/**
 * Sort `items` by distance from `origin`, nearest first.
 *
 * Items whose position is missing or unusable sort LAST, keep their relative input order, and carry
 * `distanceKm: null` rather than `0`. A missing position that compared as zero would rank an
 * unlocatable provider above every real one - the same "absence rendered as a definite value" defect
 * the module's `atan2` choice exists to avoid, one level up.
 *
 * If `origin` itself is unusable, nothing can be ranked: every item comes back with `distanceKm:
 * null` in input order. That is deliberately not an error - the caller has a list to render, it just
 * has no distances to put on it.
 *
 * The sort is stable (ECMAScript guarantees it), so equidistant items keep their input order and the
 * caller's own ordering survives as the tiebreak.
 */
export function sortByDistance<T>(
  origin: LatLng,
  items: readonly T[],
  positionOf: (item: T) => LatLng | null | undefined,
): Ranked<T>[] {
  const originUsable = isValidLatLng(origin);
  const ranked: Ranked<T>[] = items.map((item) => {
    if (!originUsable) return { item, distanceKm: null };
    const p = positionOf(item);
    return {
      item,
      distanceKm: isValidLatLng(p) ? haversineKm(origin, p) : null,
    };
  });
  return ranked.sort((x, y) => {
    if (x.distanceKm === null && y.distanceKm === null) return 0;
    if (x.distanceKm === null) return 1;
    if (y.distanceKm === null) return -1;
    return x.distanceKm - y.distanceKm;
  });
}
